### ISSUE TITLE
post_create_commands prevent autoscaler from working

### ISSUE THREAD

**Issue by Jboulery** [vitobotta/hetzner-k3s#408] opened 2024-08-08 09:59 UTC
Hey,

I have an existing cluster on Hetzner and wanted to use a gateway / NAT server to have a fixed IP that I can whitelist in third party services (e.g. databases).
Followed [this Hetzner community tutorial](https://community.hetzner.com/tutorials/how-to-set-up-nat-for-cloud-networks).

Original config (autoscaling works fine):
```yaml
hetzner_token: ...
cluster_name: x-dev
kubeconfig_path: "..."
k3s_version: v1.30.3+k3s1
public_ssh_key_path: "..."
private_ssh_key_path: "..."
use_ssh_agent: false
ssh_allowed_networks:
  - 0.0.0.0/0
api_allowed_networks:
  - 0.0.0.0/0
private_network_subnet: 10.0.0.0/16
schedule_workloads_on_masters: false
masters_pool:
  instance_type: cpx21
  instance_count: 1
  location: nbg1
worker_node_pools:
  - name: autoscaled-cpx41
    instance_type: cpx41
    instance_count: 2
    location: nbg1
    autoscaling:
      enabled: true
      min_instances: 0
      max_instances: 5
```

New config (autoscaling stops working correctly):
```yaml
hetzner_token: ...
cluster_name: x-dev
kubeconfig_path: "..."
k3s_version: v1.30.3+k3s1
public_ssh_key_path: "..."
private_ssh_key_path: "..."
use_ssh_agent: false
ssh_allowed_networks:
  - 0.0.0.0/0
api_allowed_networks:
  - 0.0.0.0/0
private_network_subnet: 10.0.0.0/16
schedule_workloads_on_masters: false
additional_packages:
  - ifupdown
post_create_commands:
  - apt update
  - apt upgrade -y
  - apt autoremove -y
  - |
    cat <<'EOF' >> /etc/systemd/network/10-ens10.network
    [Match]
    Name=ens10
    
    [Network]
    DHCP=yes
    Gateway=10.0.0.1
    EOF

masters_pool:
  instance_type: cpx21
  instance_count: 1
  location: nbg1

worker_node_pools:
  - name: autoscaled-cpx41
    instance_type: cpx41
    instance_count: 2
    location: nbg1
    autoscaling:
      enabled: true
      min_instances: 0
      max_instances: 5
```

Output:
```
Validating configuration......configuration seems valid.

=== Creating infrastructure resources ===
Network already exists, skipping.
Updating firewall...done.
SSH key already exists, skipping.
Placement group x-dev-masters already exists, skipping.
Server x-dev-cpx21-master1 already exists, skipping.
Server x-dev-cpx21-master1 already exists, skipping.
Waiting for successful ssh connectivity with server x-dev-cpx21-master1...
...server x-dev-cpx21-master1 is now up.

=== Setting up Kubernetes ===
Deploying k3s to first master x-dev-cpx21-master1...
[INFO]  Using v1.30.3+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.30.3+k3s1/sha256sum-amd64.txt
[INFO]  Skipping binary downloaded, installed k3s matches hash
[INFO]  Skipping installation of SELinux RPM
[INFO]  Skipping /usr/local/bin/kubectl symlink to k3s, already exists
[INFO]  Skipping /usr/local/bin/crictl symlink to k3s, already exists
[INFO]  Skipping /usr/local/bin/ctr symlink to k3s, already exists
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
[INFO]  No change detected so skipping service start
Waiting for the control plane to be ready...
Saving the kubeconfig file to ...
...k3s has been deployed to first master x-dev-cpx21-master1 and the control plane is up.

=== Deploying Hetzner drivers ===

Creating secret for Hetzner Cloud token...
secret/hcloud configured
...secret created.

Deploying Hetzner Cloud Controller Manager...
serviceaccount/hcloud-cloud-controller-manager unchanged
clusterrolebinding.rbac.authorization.k8s.io/system:hcloud-cloud-controller-manager unchanged
deployment.apps/hcloud-cloud-controller-manager unchanged
...Cloud Controller Manager deployed

Deploying Hetzner CSI Driver...
serviceaccount/hcloud-csi-controller unchanged
storageclass.storage.k8s.io/hcloud-volumes unchanged
clusterrole.rbac.authorization.k8s.io/hcloud-csi-controller unchanged
clusterrolebinding.rbac.authorization.k8s.io/hcloud-csi-controller unchanged
service/hcloud-csi-controller-metrics unchanged
service/hcloud-csi-node-metrics unchanged
daemonset.apps/hcloud-csi-node configured
deployment.apps/hcloud-csi-controller configured
csidriver.storage.k8s.io/csi.hetzner.cloud unchanged
...CSI Driver deployed

Deploying k3s System Upgrade Controller...
namespace/system-upgrade unchanged
serviceaccount/system-upgrade unchanged
configmap/default-controller-env unchanged
deployment.apps/system-upgrade-controller unchanged
...k3s System Upgrade Controller deployed.

Deploying Cluster Autoscaler...
serviceaccount/cluster-autoscaler unchanged
clusterrole.rbac.authorization.k8s.io/cluster-autoscaler unchanged
role.rbac.authorization.k8s.io/cluster-autoscaler unchanged
clusterrolebinding.rbac.authorization.k8s.io/cluster-autoscaler unchanged
rolebinding.rbac.authorization.k8s.io/cluster-autoscaler unchanged
deployment.apps/cluster-autoscaler configured
...Cluster Autoscaler deployed.
```

What happens next is that autoscaling won't work. When it tries to add machines to the cluster, this error occurs in the autoscaler logs:
`Failed to get node group options for autoscaled-cpx41: Not implemented`

The new machine is requested correctly (present in the Hetzner console), but won't join the cluster. Is it a bug impacting existing autoscaling configurations or what should I do differently?

Thanks!

**Comment by vitobotta** [comment] 2024-08-08 10:36
I suspect this may be due to some post create commands not being executed correctly on the autoscaled nodes, perhaps due to the yaml formatting. If you ssh into an autoscaled node, do you see the expected content in  /etc/systemd/network/10-ens10.network?

**Comment by Jboulery** [comment] 2024-08-08 13:21
You're right, it's not been created. I can probably use `ip route add` but this multiple lines command was about making the changes permanent. 
Is it happening because pipe symbol followed by a command with multiple lines isn't supported during configuration parsing? The command otherwise looked quite standard.

**Comment by vitobotta** [comment] 2024-08-08 14:31
Out of curiosity can you test with v2.rc3 (on a temp cluster! don't use it on a production cluster yet) and see if you can reproduce the same issue? I am quite busy at the moment so I can't check this before the weekend or later.

**Comment by vitobotta** [comment] 2024-08-08 14:32
> Edit: Just tried with `ip route add` instead of the bigger command and it worked fine :)

Nice! I guess we can close this? Or actually would you mind adding a PR to the `more-refactoring` branch to add this info to the docs?

**Comment by vitobotta** [comment] 2024-08-12 17:35
I am closing this, feel free to open another issue if you have others.

**Closed by vitobotta** 2024-08-12 17:35 UTC

**Comment by Jboulery** [comment] 2024-08-14 07:57
Thanks for the reply! I had a couple days off last week, will create a PR :)

**Comment by Jboulery** [comment] 2024-08-19 09:40
@vitobotta can you allow me to create a new branch so that I can create this minor PR please? 
Thanks and congrats for v2!

**Comment by vitobotta** [comment] 2024-08-19 11:53
Hi! Since the branch I mentioned has been merged, just open a PR based on main :)
