### ISSUE TITLE
Hetzner Cloud Console Account got closed down!

### ISSUE THREAD

**Issue by talkyoo** [vitobotta/hetzner-k3s#39] opened 2021-11-17 15:23 UTC
I used this create Cluster Script - see its output downstairs.

Hetzner as a result closed our Cloud Console Account, because the "Script / Tool" 
was disfunctional and made too many API Requests in the Hetzner API System.

They wrote that the script:

"Es scheint so, als ob Sie viele API Requests zum Anlegen von Servern erzeugt haben, wo der Name aber bereits an einen anderen Server vergeben wurde. Können Sie dies einmal überprüfen? Anschließend würden wir den Zugriff auf die API wieder freischalten.

Wir arbeiten bereits an einer Lösung bei uns, sodass solche API Requests keine solchen Auswirkungen mehr hat.
" 

Cheers,
rené

---
hetzner_token: "ea2*********************w"
cluster_name: "zooo-k3s"
kubeconfig_path: "../kubeconfig"
k3s_version: v1.21.3+k3s1
public_ssh_key_path: '~/.ssh/id_rsa.pub'
private_ssh_key_path: '~/.ssh/id_rsa'
ssh_allowed_networks:
  - 0.0.0.0/0
verify_host_key: false
location: fsn1
masters:
  instance_type: cpx11
  instance_count: 3
worker_node_pools:
- name: small
  instance_type: cpx11
  instance_count: 4
- name: big
  instance_type: cpx21
  instance_count: 2

OUTPUT:

Creating server zooo-k3s-cpx11-master1...
Creating server zooo-k3s-cpx11-pool-small-worker3...
Creating server zooo-k3s-cpx11-master3...
Creating server zooo-k3s-cpx11-master2...
Creating server zooo-k3s-cpx21-pool-big-worker1...
Creating server zooo-k3s-cpx11-pool-small-worker2...
Creating server zooo-k3s-cpx11-pool-small-worker1...
Creating server zooo-k3s-cpx11-pool-small-worker4...
Creating server zooo-k3s-cpx21-pool-big-worker2...
...server zooo-k3s-cpx11-pool-small-worker1 created.

Error creating server zooo-k3s-cpx11-master1. Response details below:

#<HTTP::Response/1.1 403 Forbidden {"Date"=>"Tue, 16 Nov 2021 18:03:17 GMT", "Content-Type"=>"application/json", "Content-Length"=>"98", "Connection"=>"close", "ratelimit-limit"=>"3600", "ratelimit-remaining"=>"1259", "ratelimit-reset"=>"1637088138", "x-correlation-id"=>"47ca9b2d-a61c-42fc-a263-52bc6b6be110", "Strict-Transport-Security"=>"max-age=15724800; includeSubDomains", "Access-Control-Allow-Origin"=>"*", "Access-Control-Allow-Credentials"=>"true"}>
Error creating server zooo-k3s-cpx11-pool-small-worker3. Response details below:

#<HTTP::Response/1.1 403 Forbidden {"Date"=>"Tue, 16 Nov 2021 18:03:17 GMT", "Content-Type"=>"application/json", "Content-Length"=>"98", "Connection"=>"close", "ratelimit-limit"=>"3600", "ratelimit-remaining"=>"1258", "ratelimit-reset"=>"1637088139", "x-correlation-id"=>"b37320da-4f11-4309-96f0-086424565fc4", "Strict-Transport-Security"=>"max-age=15724800; includeSubDomains", "Access-Control-Allow-Origin"=>"*", "Access-Control-Allow-Credentials"=>"true"}>
Error creating server zooo-k3s-cpx21-pool-big-worker2. Response details below:

#<HTTP::Response/1.1 403 Forbidden {"Date"=>"Tue, 16 Nov 2021 18:03:20 GMT", "Content-Type"=>"application/json", "Content-Length"=>"98", "Connection"=>"close", "ratelimit-limit"=>"3600", "ratelimit-remaining"=>"1258", "ratelimit-reset"=>"1637088142", "x-correlation-id"=>"4c983418-1542-4e4e-8793-535dee5b3040", "Strict-Transport-Security"=>"max-age=15724800; includeSubDomains", "Access-Control-Allow-Origin"=>"*", "Access-Control-Allow-Credentials"=>"true"}>
Error creating server zooo-k3s-cpx11-pool-small-worker4. Response details below:

#<HTTP::Response/1.1 403 Forbidden {"Date"=>"Tue, 16 Nov 2021 18:03:20 GMT", "Content-Type"=>"application/json", "Content-Length"=>"98", "Connection"=>"close", "ratelimit-limit"=>"3600", "ratelimit-remaining"=>"1257", "ratelimit-reset"=>"1637088143", "x-correlation-id"=>"02156b5c-be08-4009-b0bb-7e0f918bb145", "Strict-Transport-Security"=>"max-age=15724800; includeSubDomains", "Access-Control-Allow-Origin"=>"*", "Access-Control-Allow-Credentials"=>"true"}>
Error creating server zooo-k3s-cpx11-master2. Response details below:

#<HTTP::Response/1.1 403 Forbidden {"Date"=>"Tue, 16 Nov 2021 18:03:22 GMT", "Content-Type"=>"application/json", "Content-Length"=>"98", "Connection"=>"close", "ratelimit-limit"=>"3600", "ratelimit-remaining"=>"1256", "ratelimit-reset"=>"1637088146", "x-correlation-id"=>"eb8df639-e8b9-48e3-8e2e-3ac7ef5dcf07", "Strict-Transport-Security"=>"max-age=15724800; includeSubDomains", "Access-Control-Allow-Origin"=>"*", "Access-Control-Allow-Credentials"=>"true"}>
Error creating server zooo-k3s-cpx21-pool-big-worker1. Response details below:

#<HTTP::Response/1.1 403 Forbidden {"Date"=>"Tue, 16 Nov 2021 18:03:22 GMT", "Content-Type"=>"application/json", "Content-Length"=>"98", "Connection"=>"close", "ratelimit-limit"=>"3600", "ratelimit-remaining"=>"1255", "ratelimit-reset"=>"1637088147", "x-correlation-id"=>"b450319d-f78f-4fd1-b5e1-d53dcfcb75cc", "Strict-Transport-Security"=>"max-age=15724800; includeSubDomains", "Access-Control-Allow-Origin"=>"*", "Access-Control-Allow-Credentials"=>"true"}>
Error creating server zooo-k3s-cpx11-pool-small-worker2. Response details below:

#<HTTP::Response/1.1 403 Forbidden {"Date"=>"Tue, 16 Nov 2021 18:03:26 GMT", "Content-Type"=>"application/json", "Content-Length"=>"98", "Connection"=>"close", "ratelimit-limit"=>"3600", "ratelimit-remaining"=>"1253", "ratelimit-reset"=>"1637088153", "x-correlation-id"=>"7fa772e7-8629-49fd-86e6-2109707ba68e", "Strict-Transport-Security"=>"max-age=15724800; includeSubDomains", "Access-Control-Allow-Origin"=>"*", "Access-Control-Allow-Credentials"=>"true"}>
Error creating server zooo-k3s-cpx11-master3. Response details below:

#<HTTP::Response/1.1 403 Forbidden {"Date"=>"Tue, 16 Nov 2021 18:03:28 GMT", "Content-Type"=>"application/json", "Content-Length"=>"98", "Connection"=>"close", "ratelimit-limit"=>"3600", "ratelimit-remaining"=>"1253", "ratelimit-reset"=>"1637088155", "x-correlation-id"=>"09da4401-3890-48f6-8627-ea28f5cebb90", "Strict-Transport-Security"=>"max-age=15724800; includeSubDomains", "Access-Control-Allow-Origin"=>"*", "Access-Control-Allow-Credentials"=>"true"}>

**Comment by vitobotta** [comment] 2021-11-17 15:29
First, this tool is not "disfunctional". It has been used to create dozens of clusters. The tool by itself does not make many requests. Actually it makes a single request per resource. I am not sure of what happened in your case. Did you for example re-run the script right after a failed attempt or something like that?

**Comment by vitobotta** [comment] 2021-11-17 15:32
I deleted my previous message because I am investigating.

**Comment by talkyoo** [comment] 2021-11-17 15:38
"Disfuctional" said Hetzner!

**Comment by vitobotta** [comment] 2021-11-17 15:40
They choose a poor word then. 

I just created a cluster and I didn't have any issues. Like I was asking in the previous comment, did you by chance try to create a cluster soon after a failed attempt? Or what happened exactly?

**Comment by talkyoo** [comment] 2021-11-17 15:40
Yes, I did re-run the Script after the ssh errors I got, because of the wront vars used in the yaml.

But I did NOT ran it twice when ssh vars were correct.

**Comment by vitobotta** [comment] 2021-11-17 15:43
> Yes, I did re-run the Script after the ssh errors I got, because of the wront vars used in the yaml.
> 
> But I did NOT ran it twice when ssh vars were correct.

It can happen that by the time you re-run the tool, the servers were being assigned the name but didn't appear as "created" yet. Therefore when you re-run the script it attempted to create servers with names that were taken already. It has never happened to me nor reported by others so perhaps it was something temporary.

**Comment by talkyoo** [comment] 2021-11-17 15:45
So, what is a safe way to test?

We just got access back to console.hetzner.cloud. 
* I will delete all servers

What is the minimum of master and nodes needed to test the script?

**Comment by vitobotta** [comment] 2021-11-17 15:47
I would recommend you delete the project if you can and create a new one, just to make sure you start from a blank state. Can you do that? I have created a second cluster now to see if there are temporary problems with the API and again I couldn't reproduce the problem you had.

You can create a cluster with even just one master provided that you set `schedule_workloads_on_masters` to `true`.

**Comment by talkyoo** [comment] 2021-11-17 15:52
Just deleted the servers / fw / networks 
and created a new k3s project.

is this correct?

`---
hetzner_token: "ea2t**********"
cluster_name: "zooo-k3s"
kubeconfig_path: "../kubeconfig"
k3s_version: v1.21.3+k3s1
public_ssh_key_path: '~/.ssh/id_rsa.pub'
private_ssh_key_path: '~/.ssh/id_rsa'
ssh_allowed_networks:
  - 0.0.0.0/0
verify_host_key: false
schedule_workloads_on_masters: true
location: fsn1
masters:
  instance_type: cpx11
  instance_count: 1`

**Comment by vitobotta** [comment] 2021-11-17 15:55
The SSH key paths in your config start with "/". You probably meant "~/.ssh", right? Which OS are you on?

**Comment by talkyoo** [comment] 2021-11-17 15:56
What am I doing wrong?


'rene@LIEFERICKSON:/mnt/c/Users/rene/infrastructure/hetzner-k3s$ hetzner-k3s create-cluster --config-file=./zooo-k3s-hetzner.yaml
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/any.rb:5: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/definition.rb:30: warning: The called method `initialize' is defined here
/var/lib/gems/2.7.0/gems/dry-logic-0.6.1/lib/dry/logic/rule.rb:83: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/var/lib/gems/2.7.0/gems/dry-logic-0.6.1/lib/dry/logic/rule.rb:44: warning: The called method `build' is defined here
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/decorator.rb:13: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/options.rb:8: warning: The called method `initialize' is defined here
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/sum.rb:43: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/options.rb:8: warning: The called method `initialize' is defined here
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/constructor.rb:122: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/constructor.rb:20: warning: The called method `new' is defined here
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/array/member.rb:13: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/definition.rb:30: warning: The called method `initialize' is defined here

Creating placement group...
...placement group created.


Creating firewall...
...firewall created.


Creating private network...
...private network created.


Creating SSH key...
...SSH key created.

/var/lib/gems/2.7.0/gems/hetzner-k3s-0.4.7/lib/hetzner/k3s/cluster.rb:156: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/var/lib/gems/2.7.0/gems/hetzner-k3s-0.4.7/lib/hetzner/infra/server.rb:8: warning: The called method `create' is defined here

Creating server zooo-k3s-cpx11-master1...
...server zooo-k3s-cpx11-master1 created.


Waiting for server zooo-k3s-cpx11-master1 to be up...
Waiting for server zooo-k3s-cpx11-master1 to be up...
Waiting for server zooo-k3s-cpx11-master1 to be up...
Waiting for server zooo-k3s-cpx11-master1 to be up...
Waiting for server zooo-k3s-cpx11-master1 to be up...
Waiting for server zooo-k3s-cpx11-master1 to be up...
Waiting for server zooo-k3s-cpx11-master1 to be up...
Waiting for server zooo-k3s-cpx11-master1 to be up...
...server zooo-k3s-cpx11-master1 is now up.

Deploying k3s to first master (zooo-k3s-cpx11-master1)...
[INFO]  Using v1.21.3+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.21.3+k3s1/sha256sum-amd64.txt
[INFO]  Downloading binary https://github.com/k3s-io/k3s/releases/download/v1.21.3+k3s1/k3s
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Skipping installation of SELinux RPM
[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
[INFO]  Creating /usr/local/bin/ctr symlink to k3s
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
[INFO]  systemd: Starting k3s

...k3s has been deployed to first master.

Deploying Hetzner Cloud Controller Manager...
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/hetzner-k3s-0.4.7/lib/hetzner/k3s/cluster.rb:327: warning: Passing the keyword argument as the last hash parameter is deprecated
/var/lib/gems/2.7.0/gems/k8s-ruby-0.10.5/lib/k8s/resource.rb:45: warning: The called method `initialize' is defined here
/var/lib/gems/2.7.0/gems/recursive-open-struct-1.1.3/lib/recursive_open_struct.rb:188: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/var/lib/gems/2.7.0/gems/k8s-ruby-0.10.5/lib/k8s/resource.rb:45: warning: The called method `initialize' is defined here
Traceback (most recent call last):
        13: from /usr/local/bin/hetzner-k3s:23:in `<main>'
        12: from /usr/local/bin/hetzner-k3s:23:in `load'
        11: from /var/lib/gems/2.7.0/gems/hetzner-k3s-0.4.7/exe/hetzner-k3s:4:in `<top (required)>'
        10: from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
         9: from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
         8: from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
         7: from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
         6: from /var/lib/gems/2.7.0/gems/hetzner-k3s-0.4.7/lib/hetzner/k3s/cli.rb:28:in `create_cluster'
         5: from /var/lib/gems/2.7.0/gems/hetzner-k3s-0.4.7/lib/hetzner/k3s/cluster.rb:46:in `create'
         4: from /var/lib/gems/2.7.0/gems/hetzner-k3s-0.4.7/lib/hetzner/k3s/cluster.rb:348:in `deploy_cloud_controller_manager'
         3: from /var/lib/gems/2.7.0/gems/k8s-ruby-0.10.5/lib/k8s/resource.rb:38:in `from_files'
         2: from /var/lib/gems/2.7.0/gems/yaml-safe_load_stream-0.1.1/lib/yaml/safe_load_stream.rb:56:in `safe_load_stream'
         1: from /var/lib/gems/2.7.0/gems/yaml-safe_load_stream-0.1.1/lib/yaml/safe_load_stream.rb:16:in `safe_load_stream'
/var/lib/gems/2.7.0/gems/psych-4.0.2/lib/psych.rb:452:in `parse_stream': wrong number of arguments (given 2, expected 1) (ArgumentError)
rene@LIEFERICKSON:/mnt/c/Users/rene/infrastructure/hetzner-k3s$'

**Comment by talkyoo** [comment] 2021-11-17 16:08
I am on a Ubuntu 20.04 running under W10.

my create_cluster.yaml states

public_ssh_key_path: '~/.ssh/id_rsa.pub'
private_ssh_key_path: '~/.ssh/id_rsa'

and

rene@LIEFERICKSON:/mnt/c/Users/rene/infrastructure/hetzner-k3s$ ruby -v
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]

**Comment by talkyoo** [comment] 2021-11-17 16:09
aha - the github tex-editor does add the slashes!

**Comment by vitobotta** [comment] 2021-11-17 16:15
It's likely the version of Ruby. Can you try Ruby 2.7.2 or just use the Docker image so you don't have to worry about Ruby?

**Comment by vitobotta** [comment] 2021-11-17 16:17
I mentioned in the README though that Ruby 2.7.2 or higher in the 2.7.x series is recommended. I haven't tested with Ruby 3 yet. But anyway yeah, if you don't want to worry about Ruby just use the Docker image. Make sure you follow the README with that because for example the kubeconfig path is slightly different when using the Docker image.

**Comment by talkyoo** [comment] 2021-11-17 16:24
I am just in the process of setting up a fresh ubuntu server for ruby on hetzner.

BTW:



Here is the "technical" reply from Hetzer:

Translated with deepl and in german further down:

"
The external `hetzner-k3s` script can apparently fall into persistent error states in unfavorable cases:

The HTTP client (https://github.com/vitobotta/hetzner-k3s/blob/main/lib/hetzner/infra/client.rb#L39) uses a timeout of 5s, and seems to repeat the request infinitely.

Especially the creation of servers can sometimes take longer.

Furthermore, all servers seem to be created in parallel: https://github.com/vitobotta/hetzner-k3s/blob/main/lib/hetzner/k3s/cluster.rb#L156.


The parallel and endlessly repeating requests for server creation occurred yesterday around shortly before 6pm, and caused bottlenecks.
 

Kind regards"




ORIGINAL:

"Das externe `hetzner-k3s` Script kann scheinbar im ungünstigen Fällen scheinbar in dauerhafte Fehlerzustände fallen:

Der HTTP Client (https://github.com/vitobotta/hetzner-k3s/blob/main/lib/hetzner/infra/client.rb#L39) nutzt einen Timeout von 5s, und scheint den Request unendlich zu wiederholen.

Insbesondere die Erstellung von Servern kann zum Teil länger dauern.

Weiterhin werden alle Server scheinbar parallel erstellt: https://github.com/vitobotta/hetzner-k3s/blob/main/lib/hetzner/k3s/cluster.rb#L156

Die parallelen und sich endlose wiederholenden Requests für die Erstellung der Server sind gestern gegen kurz vor 18 Uhr aufgetreten, und haben zu Engpässen geführt.
 
Mit freundlichen Grüßen / Kind regards"

**Comment by vitobotta** [comment] 2021-11-17 16:27
I never had problems with this but if they say timeout is short it's better to increase it. I will do it in the next release. Thanks for sharing this. I will also limit the retries to 3 or something like that.

**Comment by vitobotta** [comment] 2021-11-17 16:39
I've already release v0.4.8 with the timeout increased to 30 seconds and max 3 retries for an API call. Hopefully this should help preventing your issue from happening again. So please make sure you use the newest release.

**Comment by talkyoo** [comment] 2021-11-17 16:51
Great - I will report back asap!

**Comment by vitobotta** [comment] 2021-11-17 16:53
👍

**Comment by talkyoo** [comment] 2021-11-17 19:30
seems to have been successful - used docker method, did not find fast way to install ruby 2.7.2 only 2.7.0.
I am nervous now :-)

'root@ubuntu-k3s-setup:~/hetzner-k3s# docker run --rm -it -v ${PWD}:/cluster -v ${HOME}/.ssh:/tmp/.ssh vitobotta/hetzner-k3s:v0.4.8 create-cluster --config-file /cluster/zooo-k3s.yaml

Creating placement group...
...placement group created.


Creating firewall...
...firewall created.



Creating private network...
...private network created.


Creating SSH key...
...SSH key created.


Creating server test-cpx21-master1...
...server test-cpx21-master1 created.


Waiting for server test-cpx21-master1 to be up...
Waiting for server test-cpx21-master1 to be up...
Waiting for server test-cpx21-master1 to be up...
Waiting for server test-cpx21-master1 to be up...
Waiting for server test-cpx21-master1 to be up...
Waiting for server test-cpx21-master1 to be up...
Waiting for server test-cpx21-master1 to be up...
...server test-cpx21-master1 is now up.

Deploying k3s to first master (test-cpx21-master1)...
[INFO]  Using v1.21.3+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.21.3+k3s1/sha256sum-amd64.txt
[INFO]  Downloading binary https://github.com/k3s-io/k3s/releases/download/v1.21.3+k3s1/k3s
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Skipping installation of SELinux RPM
[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
[INFO]  Creating /usr/local/bin/ctr symlink to k3s
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
[INFO]  systemd: Starting k3s

...k3s has been deployed to first master.

Deploying Hetzner Cloud Controller Manager...
...Cloud Controller Manager deployed

Deploying Hetzner CSI Driver...
...CSI Driver deployed

Deploying k3s System Upgrade Controller...
...k3s System Upgrade Controller deployed
root@ubuntu-k3s-setup:~/hetzner-k3s#'

**Comment by vitobotta** [comment] 2021-11-17 20:50
So all good now?

**Comment by talkyoo** [comment] 2021-11-18 14:28
Thanks - Yes, Yes! 

Just have to figure out why kubectl on my mac does not like the k3s.yaml from the master.

kubectl says: Error in configuration: context was noct found for specified context: default.

I run an old K8S cluster v1.15 - guess some things changed to latest k3s.

**Comment by talkyoo** [comment] 2021-11-18 15:59
Got aordpress deployed - now need to lean about this loadbalancer and hetzner.

**Comment by vitobotta** [comment] 2021-11-18 16:14
Awesome glad you got it working in the end :)

**Comment by talkyoo** [comment] 2021-11-18 16:21
Thanks for the great tool!

**Comment by vitobotta** [comment] 2021-11-18 16:29
Thank you again for sharing the replies from Hetzner, very useful. I'm closing for now but feel free to reopen or open a new one if you have some issues again.

**Closed by vitobotta** 2021-11-18 16:29 UTC
