### ISSUE TITLE
Unable to create cluster

### ISSUE THREAD

**Issue by MatusBoa** [vitobotta/hetzner-k3s#32] opened 2021-11-03 17:00 UTC
Hello,

I tried to create cluster via docker (`docker run --rm -it -v ${PWD}:/cluster -v ${HOME}/.ssh:/tmp/.ssh vitobotta/hetzner-k3s:v0.4.4 create-cluster --config-file /cluster/cluster.yaml`)

My config looks like this

```yaml
---
hetzner_token: xxx
cluster_name: test
kubeconfig_path: "./kubeconfig"
k3s_version: v1.21.3+k3s1
public_ssh_key_path: "~/.ssh/id_rsa.pub"
private_ssh_key_path: "~/.ssh/id_rsa"
ssh_allowed_networks:
  - 0.0.0.0/0
verify_host_key: false
location: nbg1
schedule_workloads_on_masters: false
masters:
  instance_type: cx11
  instance_count: 1
worker_node_pools:
- name: small
  instance_type: cx21
  instance_count: 1
```

But it gave me this error:

```

Placement group already exists, skipping.


Firewall already exists, skipping.


Private network already exists, skipping.


SSH key already exists, skipping.



Creating server test-cx11-master1...
Creating server test-cx21-pool-small-worker1...
...server test-cx11-master1 created.

...server test-cx21-pool-small-worker1 created.


#<Thread:0x000000400a44ec98 /usr/local/bundle/gems/hetzner-k3s-0.4.4/lib/hetzner/k3s/cluster.rb:162 run> terminated with exception (report_on_exception is true):
[1mTraceback[m (most recent call last):
	7: from /usr/local/bundle/gems/hetzner-k3s-0.4.4/lib/hetzner/k3s/cluster.rb:162:in `block (2 levels) in create_resources'
	6: from /usr/local/bundle/gems/hetzner-k3s-0.4.4/lib/hetzner/k3s/cluster.rb:454:in `wait_for_ssh'
	5: from /usr/local/lib/ruby/2.7.0/timeout.rb:110:in `timeout'
	4: from /usr/local/lib/ruby/2.7.0/timeout.rb:33:in `catch'
	3: from /usr/local/lib/ruby/2.7.0/timeout.rb:33:in `catch'
	2: from /usr/local/lib/ruby/2.7.0/timeout.rb:33:in `block in catch'
	1: from /usr/local/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
/usr/local/bundle/gems/hetzner-k3s-0.4.4/lib/hetzner/k3s/cluster.rb:455:in `block in wait_for_ssh': [1mundefined method `[]' for nil:NilClass ([1;4mNoMethodError[m[1m)[m
#<Thread:0x000000400a44eba8 /usr/local/bundle/gems/hetzner-k3s-0.4.4/lib/hetzner/k3s/cluster.rb:162 run> terminated with exception (report_on_exception is true):
[1mTraceback[m (most recent call last):
	7: from /usr/local/bundle/gems/hetzner-k3s-0.4.4/lib/hetzner/k3s/cluster.rb:162:in `block (2 levels) in create_resources'
	6: from /usr/local/bundle/gems/hetzner-k3s-0.4.4/lib/hetzner/k3s/cluster.rb:454:in `wait_for_ssh'
	5: from /usr/local/lib/ruby/2.7.0/timeout.rb:110:in `timeout'
	4: from /usr/local/lib/ruby/2.7.0/timeout.rb:33:in `catch'
	3: from /usr/local/lib/ruby/2.7.0/timeout.rb:33:in `catch'
	2: from /usr/local/lib/ruby/2.7.0/timeout.rb:33:in `block in catch'
	1: from /usr/local/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
/usr/local/bundle/gems/hetzner-k3s-0.4.4/lib/hetzner/k3s/cluster.rb:455:in `block in wait_for_ssh': [1mundefined method `[]' for nil:NilClass ([1;4mNoMethodError[m[1m)[m
[1mTraceback[m (most recent call last):
	7: from /usr/local/bundle/gems/hetzner-k3s-0.4.4/lib/hetzner/k3s/cluster.rb:162:in `block (2 levels) in create_resources'
	6: from /usr/local/bundle/gems/hetzner-k3s-0.4.4/lib/hetzner/k3s/cluster.rb:454:in `wait_for_ssh'
	5: from /usr/local/lib/ruby/2.7.0/timeout.rb:110:in `timeout'
	4: from /usr/local/lib/ruby/2.7.0/timeout.rb:33:in `catch'
	3: from /usr/local/lib/ruby/2.7.0/timeout.rb:33:in `catch'
	2: from /usr/local/lib/ruby/2.7.0/timeout.rb:33:in `block in catch'
	1: from /usr/local/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
/usr/local/bundle/gems/hetzner-k3s-0.4.4/lib/hetzner/k3s/cluster.rb:455:in `block in wait_for_ssh': [1mundefined method `[]' for nil:NilClass ([1;4mNoMethodError[m[1m)[m
```

**Comment by vitobotta** [comment] 2021-11-03 17:30
Hi, there was a bug introduced in the version I released a couple of hours ago when adding support for the new US location. This should be fixed now. The Docker image is now available - please use version 0.4.5.

Also please note that, as explained in the README, the kubeconfig_path should be set to `/cluster/kubeconfig` if you use Docker.

**Comment by MatusBoa** [comment] 2021-11-03 17:38
Updated my kubeconfig_path, also tried with new version but looks like same error happened

Command i tried `docker run --rm -it -v ${PWD}:/cluster -v ${HOME}/.ssh:/tmp/.ssh vitobotta/hetzner-k3s:v0.4.5 create-cluster --config-file /cluster/cluster.yaml`

Current config

```yaml
---
hetzner_token: xxx
cluster_name: test
kubeconfig_path: "/cluster/kubeconfig"
k3s_version: v1.21.3+k3s1
public_ssh_key_path: "~/.ssh/id_rsa.pub"
private_ssh_key_path: "~/.ssh/id_rsa"
ssh_allowed_networks:
  - 0.0.0.0/0
verify_host_key: false
location: nbg1
schedule_workloads_on_masters: false
masters:
  instance_type: cx11
  instance_count: 1
worker_node_pools:
- name: small
  instance_type: cx21
  instance_count: 1
```

```

Placement group already exists, skipping.


Firewall already exists, skipping.


Private network already exists, skipping.


SSH key already exists, skipping.



Creating server test-cx11-master1...
Creating server test-cx21-pool-small-worker1...
...server test-cx21-pool-small-worker1 created.

...server test-cx11-master1 created.


#<Thread:0x000000400a29a988 /usr/local/bundle/gems/hetzner-k3s-0.4.5/lib/hetzner/k3s/cluster.rb:162 run> terminated with exception (report_on_exception is true):
[1mTraceback[m (most recent call last):
	7: from /usr/local/bundle/gems/hetzner-k3s-0.4.5/lib/hetzner/k3s/cluster.rb:162:in `block (2 levels) in create_resources'
	6: from /usr/local/bundle/gems/hetzner-k3s-0.4.5/lib/hetzner/k3s/cluster.rb:454:in `wait_for_ssh'
	5: from /usr/local/lib/ruby/2.7.0/timeout.rb:110:in `timeout'
	4: from /usr/local/lib/ruby/2.7.0/timeout.rb:33:in `catch'
	3: from /usr/local/lib/ruby/2.7.0/timeout.rb:33:in `catch'
	2: from /usr/local/lib/ruby/2.7.0/timeout.rb:33:in `block in catch'
	1: from /usr/local/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
/usr/local/bundle/gems/hetzner-k3s-0.4.5/lib/hetzner/k3s/cluster.rb:455:in `block in wait_for_ssh': [1mundefined method `[]' for nil:NilClass ([1;4mNoMethodError[m[1m)[m
#<Thread:0x000000400a29aa78 /usr/local/bundle/gems/hetzner-k3s-0.4.5/lib/hetzner/k3s/cluster.rb:162 run> terminated with exception (report_on_exception is true):
[1mTraceback[m (most recent call last):
	7: from /usr/local/bundle/gems/hetzner-k3s-0.4.5/lib/hetzner/k3s/cluster.rb:162:in `block (2 levels) in create_resources'
	6: from /usr/local/bundle/gems/hetzner-k3s-0.4.5/lib/hetzner/k3s/cluster.rb:454:in `wait_for_ssh'
	5: from /usr/local/lib/ruby/2.7.0/timeout.rb:110:in `timeout'
	4: from /usr/local/lib/ruby/2.7.0/timeout.rb:33:in `catch'
	3: from /usr/local/lib/ruby/2.7.0/timeout.rb:33:in `catch'
	2: from /usr/local/lib/ruby/2.7.0/timeout.rb:33:in `block in catch'
	1: from /usr/local/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
/usr/local/bundle/gems/hetzner-k3s-0.4.5/lib/hetzner/k3s/cluster.rb:455:in `block in wait_for_ssh': [1mundefined method `[]' for nil:NilClass ([1;4mNoMethodError[m[1m)[m
[1mTraceback[m (most recent call last):
	7: from /usr/local/bundle/gems/hetzner-k3s-0.4.5/lib/hetzner/k3s/cluster.rb:162:in `block (2 levels) in create_resources'
	6: from /usr/local/bundle/gems/hetzner-k3s-0.4.5/lib/hetzner/k3s/cluster.rb:454:in `wait_for_ssh'
	5: from /usr/local/lib/ruby/2.7.0/timeout.rb:110:in `timeout'
	4: from /usr/local/lib/ruby/2.7.0/timeout.rb:33:in `catch'
	3: from /usr/local/lib/ruby/2.7.0/timeout.rb:33:in `catch'
	2: from /usr/local/lib/ruby/2.7.0/timeout.rb:33:in `block in catch'
	1: from /usr/local/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
/usr/local/bundle/gems/hetzner-k3s-0.4.5/lib/hetzner/k3s/cluster.rb:455:in `block in wait_for_ssh': [1mundefined method `[]' for nil:NilClass ([1;4mNoMethodError[m[1m)[m
```

**Comment by vitobotta** [comment] 2021-11-03 17:45
I just tried with your same config and the cluster was created successfully. Can you try again? Wonder if there was a temporary hiccup with the API or something.

**Comment by MatusBoa** [comment] 2021-11-03 17:53
Does not work 😢 

I will try it again tomorrow.

**Comment by MatusBoa** [comment] 2021-11-04 06:02
Few hours lates..

Same error being thrown 😢

**Comment by vitobotta** [comment] 2021-11-04 09:07
Can you please try deleting the docker image from your system and running the command again after that? The weird thing is that you seem to be running into an issue with network creation that was introduced in 0.4.4, but it's definitely fixed in 0.4.5. It seems like your command was actually running 0.4.4 which is super weird.

So yeah can you delete the image locally and try again, just in case something funny happened with Docker on your Mac? I can definitely create clusters without any issues in all locations with 0.4.5.

**Comment by MatusBoa** [comment] 2021-11-04 09:41
Nothing happened to my docker, im working with it every day. Tried to remove image, it pulled it again but same thing.

**Comment by vitobotta** [comment] 2021-11-04 11:32
Do other resources (firewall, network etc) get created?

**Comment by MatusBoa** [comment] 2021-11-04 13:29
Yes, it created firewall, network and ssh key. But no servers. Tried to remove all resources, it created it again but same error.

**Comment by vitobotta** [comment] 2021-11-04 13:34
The reason I asked about other resources was to check if leftovers from previous attempts could cause problems. Have you also tried with a new project just in case? Unfortunately I was not able to reproduce the issue you're having, with 0.4.5. I created several clusters in the meantime without any errors.

**Comment by MatusBoa** [comment] 2021-11-04 13:40
Uhhh, it works perfectly for new project.. 😅

**Comment by vitobotta** [comment] 2021-11-04 13:41
Awesome! I bet that there was some leftover still in the other project which you may have not noticed :D

**Comment by vitobotta** [comment] 2021-11-04 13:42
I'll close this but feel free to open another one if you run into other issues :)

**Closed by vitobotta** 2021-11-04 13:42 UTC
