### ISSUE TITLE
Failed to create Hetzner Cloud secret

### ISSUE THREAD

**Issue by vdveldet** [vitobotta/hetzner-k3s#366] opened 2024-05-21 16:45 UTC
During deployment the following issue occurred.

```
root:/local# hetzner-k3s-linux-amd64 create --config cluster_config.yaml
Validating configuration......configuration seems valid.

=== Creating infrastructure resources ===
Network already exists, skipping.
Updating firewall...done.
SSH key already exists, skipping.
Placement group test-masters already exists, skipping.
Placement group test-small-1 already exists, skipping.
Server test-cx21-pool-small-worker1 already exists, skipping.
Server test-cx21-master1 already exists, skipping.
Server test-cx21-pool-small-worker2 already exists, skipping.
Server test-cx21-master1 already exists, skipping.
Waiting for successful ssh connectivity with server test-cx21-master1...
Server test-cx21-pool-small-worker1 already exists, skipping.
Waiting for successful ssh connectivity with server test-cx21-pool-small-worker1...
Server test-cx21-pool-small-worker2 already exists, skipping.
Waiting for successful ssh connectivity with server test-cx21-pool-small-worker2...
...server test-cx21-master1 is now up.
...server test-cx21-pool-small-worker1 is now up.
...server test-cx21-pool-small-worker2 is now up.

=== Setting up Kubernetes ===
Deploying k3s to first master test-cx21-master1...
[INFO]  Using v1.28.9+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.28.9+k3s1/sha256sum-amd64.txt
[INFO]  Skipping binary downloaded, installed k3s matches hash
[INFO]  Skipping installation of SELinux RPM
[INFO]  Skipping /usr/local/bin/kubectl symlink to k3s, already exists
[INFO]  Skipping /usr/local/bin/crictl symlink to k3s, already exists
[INFO]  Skipping /usr/local/bin/ctr symlink to k3s, already exists
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
[INFO]  No change detected so skipping service start
Waiting for the control plane to be ready...
Saving the kubeconfig file to /local/kubeconfig...
...k3s has been deployed to first master test-cx21-master1 and the control plane is up.
Deploying k3s to worker test-cx21-pool-small-worker1...
Deploying k3s to worker test-cx21-pool-small-worker2...
[INFO]  Using v1.28.9+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.28.9+k3s1/sha256sum-amd64.txt
[INFO]  Using v1.28.9+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.28.9+k3s1/sha256sum-amd64.txt
[INFO]  Skipping binary downloaded, installed k3s matches hash
[INFO]  Skipping installation of SELinux RPM
[INFO]  Skipping /usr/local/bin/kubectl symlink to k3s, already exists
[INFO]  Skipping /usr/local/bin/crictl symlink to k3s, already exists
[INFO]  Skipping /usr/local/bin/ctr symlink to k3s, already exists
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-agent-uninstall.sh
[INFO]  Skipping binary downloaded, installed k3s matches hash
[INFO]  Skipping installation of SELinux RPM
[INFO]  Skipping /usr/local/bin/kubectl symlink to k3s, already exists
[INFO]  Skipping /usr/local/bin/crictl symlink to k3s, already exists
[INFO]  Skipping /usr/local/bin/ctr symlink to k3s, already exists
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-agent-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s-agent.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s-agent.service
[INFO]  systemd: Enabling k3s-agent unit
[INFO]  env: Creating environment file /etc/systemd/system/k3s-agent.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s-agent.service
[INFO]  systemd: Enabling k3s-agent unit
[INFO]  No change detected so skipping service start
[INFO]  No change detected so skipping service start
...k3s has been deployed to worker test-cx21-pool-small-worker2.
...k3s has been deployed to worker test-cx21-pool-small-worker1.

=== Deploying Hetzner drivers ===

Creating secret for Hetzner Cloud token...
error: error validating "STDIN": error validating data: failed to download openapi: the server is currently unable to handle the request; if you choose to ignore these errors, turn validation off with --validate=false
Failed to create Hetzner Cloud secret:
#<Util::Shell::Result:0x7fb35eea9580>

```
Looks like K3s is deployed but nothing is in there....
```
kubectl get nodes
NAME                           STATUS   ROLES                       AGE   VERSION
test-cx21-master1              Ready    control-plane,etcd,master   14m   v1.28.9+k3s1
test-cx21-pool-small-worker1   Ready    <none>                      13m   v1.28.9+k3s1
test-cx21-pool-small-worker2   Ready    <none>                      13m   v1.28.9+k3s1

kubectl get pods -A
NAMESPACE     NAME                      READY   STATUS    RESTARTS   AGE
kube-system   coredns-6799fbcd5-2kgz6   0/1     Pending   0          14m

```

**Comment by vitobotta** [comment] 2024-05-21 16:51
Hi! Sometimes it can happen that the control plane is not ready yet when the tool attempts to install stuff, so you see an error similar to what you have seen. This is addressed in the upcoming version 2.0 but can still happen to the current stable.

In these cases, you can just rerun the `create` command and it will pick up from where it left. So yeah please try rerunning it :)

**Comment by vdveldet** [comment] 2024-05-22 07:41
I get the error when trying to deploy with v1.28.9+k3s1 or above.

When using v1.27.6+k3s1, the installation continues and installation finished.

I do not see the loadbalancer yet, but there must be a difference in k3s version usage

```

root:/local# /usr/local/bin/hetzner-k3s-linux-amd64 create --config cluster_config.yaml
Validating configuration......configuration seems valid.

=== Creating infrastructure resources ===
Creating network...done.
Creating firewall...done.
SSH key already exists, skipping.
Creating placement group test-masters...done.
Placement group test-small-1 already exists, skipping.
Creating server test-cx21-pool-small-worker2...
Creating server test-cx21-pool-small-worker1...
Creating server test-cx21-master1...
...server test-cx21-pool-small-worker2 created.
...server test-cx21-pool-small-worker1 created.
...server test-cx21-master1 created.
Server test-cx21-master1 already exists, skipping.
Waiting for successful ssh connectivity with server test-cx21-master1...
Server test-cx21-pool-small-worker1 already exists, skipping.
Waiting for successful ssh connectivity with server test-cx21-pool-small-worker1...
Server test-cx21-pool-small-worker2 already exists, skipping.
Waiting for successful ssh connectivity with server test-cx21-pool-small-worker2...
...server test-cx21-pool-small-worker2 is now up.
...server test-cx21-master1 is now up.
...server test-cx21-pool-small-worker1 is now up.

=== Setting up Kubernetes ===
Deploying k3s to first master test-cx21-master1...
[INFO]  Using v1.27.6+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.27.6+k3s1/sha256sum-amd64.txt
[INFO]  Downloading binary https://github.com/k3s-io/k3s/releases/download/v1.27.6+k3s1/k3s
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Skipping installation of SELinux RPM
[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
[INFO]  Creating /usr/local/bin/ctr symlink to k3s
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
[INFO]  systemd: Starting k3s
Waiting for the control plane to be ready...
Saving the kubeconfig file to /local/kubeconfig...
...k3s has been deployed to first master test-cx21-master1 and the control plane is up.
Deploying k3s to worker test-cx21-pool-small-worker1...
Deploying k3s to worker test-cx21-pool-small-worker2...
[INFO]  Using v1.27.6+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.27.6+k3s1/sha256sum-amd64.txt
[INFO]  Using v1.27.6+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.27.6+k3s1/sha256sum-amd64.txt
[INFO]  Downloading binary https://github.com/k3s-io/k3s/releases/download/v1.27.6+k3s1/k3s
[INFO]  Downloading binary https://github.com/k3s-io/k3s/releases/download/v1.27.6+k3s1/k3s
[INFO]  Verifying binary download
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Skipping installation of SELinux RPM
[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
[INFO]  Creating /usr/local/bin/ctr symlink to k3s
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-agent-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s-agent.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s-agent.service
[INFO]  systemd: Enabling k3s-agent unit
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Skipping installation of SELinux RPM
[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
[INFO]  Creating /usr/local/bin/ctr symlink to k3s
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-agent-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s-agent.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s-agent.service
[INFO]  systemd: Enabling k3s-agent unit
[INFO]  systemd: Starting k3s-agent
[INFO]  systemd: Starting k3s-agent
...k3s has been deployed to worker test-cx21-pool-small-worker2.
...k3s has been deployed to worker test-cx21-pool-small-worker1.

=== Deploying Hetzner drivers ===

Creating secret for Hetzner Cloud token...
secret/hcloud created
...secret created.

Deploying Hetzner Cloud Controller Manager...
serviceaccount/hcloud-cloud-controller-manager created
clusterrolebinding.rbac.authorization.k8s.io/system:hcloud-cloud-controller-manager created
deployment.apps/hcloud-cloud-controller-manager created
...Cloud Controller Manager deployed

Deploying Hetzner CSI Driver...
serviceaccount/hcloud-csi-controller created
storageclass.storage.k8s.io/hcloud-volumes created
clusterrole.rbac.authorization.k8s.io/hcloud-csi-controller created
clusterrolebinding.rbac.authorization.k8s.io/hcloud-csi-controller created
service/hcloud-csi-controller-metrics created
service/hcloud-csi-node-metrics created
daemonset.apps/hcloud-csi-node created
deployment.apps/hcloud-csi-controller created
csidriver.storage.k8s.io/csi.hetzner.cloud created
...CSI Driver deployed

Deploying k3s System Upgrade Controller...
namespace/system-upgrade created
serviceaccount/system-upgrade created
configmap/default-controller-env created
deployment.apps/system-upgrade-controller created
...k3s System Upgrade Controller deployed.

root:/local# hcloud load-balancer list
ID   NAME   HEALTH   IPV4   IPV6   TYPE   LOCATION   NETWORK ZONE   AGE

```

**Comment by vitobotta** [comment] 2024-05-22 08:52
Not sure about the difference 1.28 and 1.27 although I haven't come across that issue so far.

As for the load balancer, do you mean the load balancer for the Kubernetes API? If yes, that load balancer is created only when you configure the cluster in HA  mode with multiple masters. From looking at the log it seems you have created the cluster with a single master so that load balancer doesn't get created.

**Comment by vdveldet** [comment] 2024-05-22 09:11
Indeed the loadbalancer is there only with multiple masters, my bad.

I'm not able to deploy anything above 1.28 or higher.

**Comment by vitobotta** [comment] 2024-05-22 09:37
Weird. Can you reproduce the issues with 1.28 consistently with new clusters?

**Comment by TimVosch** [comment] 2024-05-23 08:24
Hey, same issue here on a brand new cluster. Trying with v1.30.1-k3s1.

```
=== Deploying Hetzner drivers ===

Creating secret for Hetzner Cloud token...
error: error validating "STDIN": error validating data: failed to download openapi: the server is currently unable to handle the request; if you choose to ignore these errors, turn validation off with --validate=false
Failed to create Hetzner Cloud secret:
#<Util::Shell::Result:0x71d52850fbc0>
```

**Comment by TimVosch** [comment] 2024-05-23 08:30
At first glance, that appears to be relevant indeed.

When `k3s kubectl describe pods -n kube-system` I get

```
 Type     Reason            Age    From               Message
  ----     ------            ----   ----               -------
  Warning  FailedScheduling  7m48s  default-scheduler  0/1 nodes are available: 1 node(s) had untolerated taint {node.cloudprovider.kubernetes.io/uninitialized: true}. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.
  Warning  FailedScheduling  6m8s   default-scheduler  0/5 nodes are available: 5 node(s) had untolerated taint {node.cloudprovider.kubernetes.io/uninitialized: true}. preemption: 0/5 nodes are available: 5 Preemption is not helpful for scheduling.
  Warning  FailedScheduling  4m47s  default-scheduler  0/5 nodes are available: 5 node(s) had untolerated taint {node.cloudprovider.kubernetes.io/uninitialized: true}. preemption: 0/5 nodes are available: 5 Preemption is not helpful for scheduling.
  Warning  FailedScheduling  3m24s  default-scheduler  0/5 nodes are available: 5 node(s) had untolerated taint {node.cloudprovider.kubernetes.io/uninitialized: true}. preemption: 0/5 nodes are available: 5 Preemption is not helpful for scheduling.
  Warning  FailedScheduling  118s   default-scheduler  0/5 nodes are available: 5 node(s) had untolerated taint {node.cloudprovider.kubernetes.io/uninitialized: true}. preemption: 0/5 nodes are available: 5 Preemption is not helpful for scheduling.
  Warning  FailedScheduling  35s    default-scheduler  0/5 nodes are available: 5 node(s) had untolerated taint {node.cloudprovider.kubernetes.io/uninitialized: true}. preemption: 0/5 nodes are available: 5 Preemption is not helpful for scheduling
```

K3s also appears to be restarting from time to time as `k3s kubectl get nodes` works, then stops, then works, etc...

**Comment by TimVosch** [comment] 2024-05-23 08:31
Just changed to `v1.29.0+k3s1` which works fine :)

**Comment by vitobotta** [comment] 2024-05-24 13:23
Closing this since it seems like an issue with k3s itself rather than with this tool. If you want to continue the conversation on this topic you can open a discussion :)

**Closed by vitobotta** 2024-05-24 13:23 UTC

**Comment by mahinthan** [comment] 2024-05-28 05:40
I believe this is something to do with the hetzner-k3s. The issue arises in two different cases.
1. Set enable_public_net_ipv4 to false and set enable_public_net_ipv6 to false
2. masters_pool instance count is set to 1

I understand for HA the masters_pool instance count is to be set to min 3. However cluster members is to be private. It is absolute must in my case.

Does anyone experience this issue when you make the cluster members to be private?
Following is the exact error
```
Creating secret for Hetzner Cloud token...
error: error validating "STDIN": error validating data: failed to download openapi: Get "http://localhost:8080/openapi/v2?timeout=32s": dial tcp [::1]:8080: connect: connection refused; if you choose to ignore these errors, turn validation off with --validate=false
Failed to create Hetzner Cloud secret:
#<Util::Shell::Result:0x7aae2845f980>
```

**Comment by vitobotta** [comment] 2024-05-28 08:02
> I believe this is something to do with the hetzner-k3s. The issue arises in two different cases.
> 
> 1. Set enable_public_net_ipv4 to false and set enable_public_net_ipv6 to false
> 2. masters_pool instance count is set to 1
> 
> I understand for HA the masters_pool instance count is to be set to min 3. However cluster members are to be public, may not be accepted for all usecases. In my case, private cluster member is absolute must.
> 
> Does anyone experience this issue when you make the cluster members to be private? Following is the exact error
> 
> ```
> Creating secret for Hetzner Cloud token...
> error: error validating "STDIN": error validating data: failed to download openapi: Get "http://localhost:8080/openapi/v2?timeout=32s": dial tcp [::1]:8080: connect: connection refused; if you choose to ignore these errors, turn validation off with --validate=false
> Failed to create Hetzner Cloud secret:
> #<Util::Shell::Result:0x7aae2845f980>
> ```

You are setting up the cluster from an instance in the same network I guess? Can you describe your setup in more detail so I can try to reproduce?

**Comment by mahinthan** [comment] 2024-05-28 12:10
> > I believe this is something to do with the hetzner-k3s. The issue arises in two different cases.
> > 
> > 1. Set enable_public_net_ipv4 to false and set enable_public_net_ipv6 to false
> > 2. masters_pool instance count is set to 1
> > 
> > I understand for HA the masters_pool instance count is to be set to min 3. However cluster members are to be public, may not be accepted for all usecases. In my case, private cluster member is absolute must.
> > Does anyone experience this issue when you make the cluster members to be private? Following is the exact error
> > ```
> > Creating secret for Hetzner Cloud token...
> > error: error validating "STDIN": error validating data: failed to download openapi: Get "http://localhost:8080/openapi/v2?timeout=32s": dial tcp [::1]:8080: connect: connection refused; if you choose to ignore these errors, turn validation off with --validate=false
> > Failed to create Hetzner Cloud secret:
> > #<Util::Shell::Result:0x7aae2845f980>
> > ```
> 
> You are setting up the cluster from an instance in the same network I guess? Can you describe your setup in more detail so I can try to reproduce?

I create a AMD server with 1 vCPU with Ubuntu OS manually. I assign public IP address and assign it into a private network (network-1). No firewall is assigned for this server. I install the kubectl and hetzner-k3s (AMD version) on this server. I have connected to this server from terminal and executed the ssh-keygen command and added that SSH key into the hetzner portal.

I copy the following configuration file into the home directory of the server and run the command. "hetzner-k3s create --config cluster_config.yaml"

```
hetzner_token: LiVOZR......
cluster_name: test
kubeconfig_path: "./kubeconfig"
k3s_version: v1.30.1+k3s1
public_ssh_key_path: "~/.ssh/id_rsa.pub"
private_ssh_key_path: "~/.ssh/id_rsa"
use_ssh_agent: false # set to true if your key has a passphrase or if SSH connections don't work or seem to hang without agent. See https://github.com/vitobotta/hetzner-k3s#limitations
# ssh_port: 22
ssh_allowed_networks:
  - 0.0.0.0/0 # ensure your current IP is included in the range
api_allowed_networks:
  - 0.0.0.0/0 # ensure your current IP is included in the range
private_network_subnet: 10.0.0.0/16 # ensure this doesn't overlap with other networks in the same project
disable_flannel: false # set to true if you want to install a different CNI
schedule_workloads_on_masters: false
enable_public_net_ipv4: false # default is true
enable_public_net_ipv6: false # default is true
datastore:
  mode: etcd # etcd (default) or external
  external_datastore_endpoint: postgres://....
masters_pool:
  instance_type: cpx11
  instance_count: 3
  location: nbg1
worker_node_pools:
- name: small-static
  instance_type: cpx11
  instance_count: 2
  location: nbg1
existing_network: network-1
```

Out of curiosity, I was also doing the same with the ARM variation of the server. It still throws the same error.
When I set the following properties to true, the cluster creation went well.
enable_public_net_ipv4: true
enable_public_net_ipv6: true

**Comment by vitobotta** [comment] 2024-06-01 12:00
I am taking a note to test this scenario when I have time.

**Comment by AXGKl** [comment] 2024-07-08 20:13
Same setup as @mahinthan, i.e. attempting to create the cluster from  a manually created server within the project space (with the goal of trying to avoid public v4 IPs).

Fails at 

```
=== Deploying Hetzner drivers ===

Creating secret for Hetzner Cloud token...
error: error validating "STDIN": error validating data: failed to download openapi: Get "http://localhost:8080/openapi/v2?timeout=32s": dial tcp [::1]:8080: connect: connection refused; if you choose to ignore these errors, turn validation off with --validate=false
Failed to create Hetzner Cloud secret:
#<Util::Shell::Result:0x7fbefd9ca080>
```

Fails for any k3s version I tried, from 1.27 to 1.30. 

Noteworthy: 

```
gk@nextcloud-ubuntu-4gb-nbg1-1:~/hetzner$ ls -lta
total 12
drwxrwxr-x 2 gk gk 4096 Jul  8 20:03 .
-rw------- 1 gk gk    0 Jul  8 20:03 kubeconfig
drwxr-xr-x 7 gk gk 4096 Jul  8 20:01 ..
-rw-r--r-- 1 gk gk 3574 Jul  8 19:32 config.yaml
gk@nextcloud-ubuntu-4gb-nbg1-1:~/hetzner$ cat /tmp/cli.cmd
set -euo pipefail
kubectl apply -f - <<-EOF
apiVersion: "v1"
kind: "Secret"
metadata:
  namespace: 'kube-system'
  name: 'hcloud'
stringData:
  network: "axc3"
  token: "NQkecNTPTlnlgbElei....
EOF

```

I.e. kubeconfig is **empty**, at the point where the tool tries to run the secret creation. 

=> Manually running it runs into the same error, clear:

```
~/hetzner$ /tmp/cli.cmd
error: error validating "STDIN": error validating data: failed to download openapi: Get "http://localhost:8080/openapi/v2?timeout=32s": dial tcp [::1]:8080: connect: connection refused; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by vitobotta** [comment] 2024-07-23 13:27
Can anyone help with testing the rc1 of v2? It's now available. See https://github.com/vitobotta/hetzner-k3s/discussions/385 for details. Thanks
