### ISSUE TITLE
NetworkUnavailable - Could not create route 

### ISSUE THREAD

**Issue by Agilitytime** [vitobotta/hetzner-k3s#7] opened 2021-08-16 16:48 UTC
Hi,

thank you So mutch for your Work!!!!

After i Create the K3s Cluster, i Becom on every Node te Message, that the Network is Unavailable.
(combined from similar events): Could not create route ddb43c79-3777-40bb-9a53-7d75689f101f 10.244.0.0/24 for node agirancher-cpx21-master1 after 2.331535684s: hcloud/CreateRoute: hcops/AllServersCache.ByName: agirancher-cpx21-master1 hcops/AllServersCache.getCache: not found

do you have any idea what the problem can be ? 

Thanks,
Basti

**Comment by vitobotta** [comment] 2021-08-16 17:00
Hi! :)

Did you try to create more than one cluster in the same Hetzner project by chance?

**Comment by Agilitytime** [comment] 2021-08-16 17:04
i created one and then deleted it via hetzner-k3s delete-cluster.
I Test it Again with a new Project.

**Comment by vitobotta** [comment] 2021-08-16 17:09
Perhaps something concerning the network wasn't deleted correctly for some reason or you created a new cluster very quickly soon after deleting one. The only case I've had problems with network routes was when I tried to create more than one cluster in the same project. This is because both clusters try to create routes for the same cidr. I thought of making it configurable but I think it's better to have one cluster per project. Let me know how it goes :)

**Comment by Agilitytime** [comment] 2021-08-16 17:15
![grafik](https://user-images.githubusercontent.com/62443876/129603036-027475b3-9aba-4c6c-87f3-304e749c32ef.png)
![grafik](https://user-images.githubusercontent.com/62443876/129603113-0602ec60-2adb-4b07-ab55-aa6a904ad4f6.png)

Same Problem after New Deployment and Hetzner Project.

Super cool how fast it goes !!!

**Comment by vitobotta** [comment] 2021-08-16 17:54
Yeah it's pretty quick, I love it. When I test stuff I create and delete clusters in no time :D

As for your problem, what do you see in the events/notifications in the Hetzner console?

**Comment by Agilitytime** [comment] 2021-08-16 18:21
![image](https://user-images.githubusercontent.com/62443876/129610848-ae8507ff-6320-4d4a-a9c8-f12979d04e05.png)
![image](https://user-images.githubusercontent.com/62443876/129610943-ad1a368e-b959-4ea2-a466-6f25fec95488.png)

In the Hetzner Console all Looks god.

I have already considered whether it is possibly due to the Ruby installation? 
I tried it first with a M1 Mac, which unfortunately does not work because of Ruby ...
and i use now a Fresh Ubuntu Install...

**Comment by vitobotta** [comment] 2021-08-16 18:47
I've also got an M1 :)

If the cluster was created successfully without any errors I doubt it's a problem with Ruby etc.

Seems that someone else has reported the same error in the Hetzner's CCM project https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/225 and https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/165

It's weird because it never happened to me from what I can remember. 

Did you just create a new project and a new cluster in it? Or did you create a cluster again after deleting another one? Did you see any errors in the output of the installer?

**Comment by vitobotta** [comment] 2021-08-16 18:50
Also are the servers attached to the private network?

**Comment by Agilitytime** [comment] 2021-08-16 18:56
I have created a completely new Hetzner project without server etc. 
I have only created a new API key.

I'll create a new project and send you the API token by mail, it would be interesting if it runs in your invirment without problems.

**Comment by vitobotta** [comment] 2021-08-16 19:00
Super weird. I just created a cluster twice both in Nuremberg and Helsinki just in case is something on Hetzner's side that is causing problems at the moment, but everything works fine and the routes were created correctly in both cases.

Yeah if you can share a token I can try from here with a small cluster and see if it happens to me too. Just make sure you don't create a cluster in the same project at the same time :)

**Comment by vitobotta** [comment] 2021-08-16 19:08
I created a cluster with your token successfully. No errors, all pods started and the routes were created just fine. I'll send you the kubeconfig so you can see it.

**Comment by Agilitytime** [comment] 2021-08-16 19:15
![image](https://user-images.githubusercontent.com/62443876/129617437-82aacc9a-c1b4-4009-b109-44ef1f0aee46.png)

no Warningns... all works fine.
I think it must be the Ruby installation?

**Comment by vitobotta** [comment] 2021-08-16 19:17
Well everything is possible at this point :D Which version of Ruby are you using? I'm also planning to create some all-in-one binaries that include the Ruby runtime, so that the user doesn't need to deal with Ruby directly if they are not familiar with it.

How did you install Ruby? But did you get any errors while creating the cluster?

**Comment by Agilitytime** [comment] 2021-08-16 19:40
i Recive sometimes this Error

/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/hetzner-k3s-0.3.2/lib/hetzner/k3s/cluster.rb:401: warning: Passing the keyword argument as the last hash parameter is deprecated
/var/lib/gems/2.7.0/gems/k8s-ruby-0.10.5/lib/k8s/resource.rb:45: warning: The called method `initialize' is defined here


I install a Fresh Ubuntu and then 

-->  sudo apt-get install ruby-full

ruby -v
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]

gem -v
3.1.2

gcc --version
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0


Full Error :

Deploying Hetzner Cloud Controller Manager...
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/hetzner-k3s-0.3.2/lib/hetzner/k3s/cluster.rb:322: warning: Passing the keyword argument as the last hash parameter is deprecated
/var/lib/gems/2.7.0/gems/k8s-ruby-0.10.5/lib/k8s/resource.rb:45: warning: The called method `initialize' is defined here
/var/lib/gems/2.7.0/gems/recursive-open-struct-1.1.3/lib/recursive_open_struct.rb:188: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/var/lib/gems/2.7.0/gems/k8s-ruby-0.10.5/lib/k8s/resource.rb:45: warning: The called method `initialize' is defined here
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
...Cloud Controller Manager deployed

Deploying Hetzner CSI Driver...
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/hetzner-k3s-0.3.2/lib/hetzner/k3s/cluster.rb:401: warning: Passing the keyword argument as the last hash parameter is deprecated
/var/lib/gems/2.7.0/gems/k8s-ruby-0.10.5/lib/k8s/resource.rb:45: warning: The called method `initialize' is defined here
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
...CSI Driver deployed

Deploying k3s System Upgrade Controller...
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/var/lib/gems/2.7.0/gems/dry-types-0.13.4/lib/dry/types/hash/schema.rb:151: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
...k3s System Upgrade Controller deployed

**Comment by vitobotta** [comment] 2021-08-16 20:01
I see. Can you try installing Ruby with rbenv instead? See https://github.com/rbenv/rbenv

```bash
apt install rbenv
```

Then to verify the installation:

```bash
curl -fsSL https://github.com/rbenv/rbenv-installer/raw/main/bin/rbenv-doctor | bash
```

Then install Ruby 2.7.4 (I haven't tested with 3.x yet)

```bash
rbenv install 2.7.4 && ruby global 2.7.4
```

Finally check that the version of Ruby is correct with `ruby -v`.

Then try creating a cluster again in a new project and let me know.

**Comment by Agilitytime** [comment] 2021-08-17 10:06
I test it now with 

ruby -v
ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux]

on a Fresh Ubuntu and Hetzner Project.

Until the installation i dont have Errors or Warnings...
The only problem is, the network is still Unavailable

![grafik](https://user-images.githubusercontent.com/62443876/129706675-77f76129-4c15-4cdf-bcab-da9d65ee75d8.png)

**Comment by vitobotta** [comment] 2021-08-17 10:19
> I test it now with
> 
> ruby -v
> ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux]
> 
> on a Fresh Ubuntu and Hetzner Project.
> 
> Until the installation i dont have Errors or Warnings...
> The only problem is, the network is still Unavailable
> 
> ![grafik](https://user-images.githubusercontent.com/62443876/129706675-77f76129-4c15-4cdf-bcab-da9d65ee75d8.png)

No weird messages in the ouput of the installer? I don't know what could be causing this, never happened to me. It would be super weird if it were somehow related to Ruby on Linux or something like that. But if all the resources are created correctly and the cloud controller manager is also installed correctly it can't be Ruby.

Can you share more from the logs of the controller manager pod?

**Comment by vitobotta** [comment] 2021-08-17 10:20
Also which Hetzner location are you using? Are you using Falkenstein by chance? It's the only one I haven't tried and I'm wondering if there is something different about it somehow.

**Comment by vitobotta** [comment] 2021-08-17 10:25
Just tried with Falkenstein, no problems with that either.

**Comment by vitobotta** [comment] 2021-08-17 11:19
Hey I was able to reproduce the problem on Linux and I think I found a fix :) I will release a new version tonight after my day job :)

**Comment by vitobotta** [comment] 2021-08-17 11:25
@Agilitytime Actually I release 0.3.3 already with a tiny change. So to test:

- install rbenv and Ruby 2.74
- ensure Ruby 2.7.4 is active (ruby -v)
- install the hetzner-k3s gem again so it updates the executable
- try again creating a cluster (delete the previous if any and wait a little bit before creating a new one if in the same project)

Let me know how it goes.

**Comment by Agilitytime** [comment] 2021-08-17 11:45
![grafik](https://user-images.githubusercontent.com/62443876/129719460-846bb370-1474-4393-a36a-75b33803c599.png)
![grafik](https://user-images.githubusercontent.com/62443876/129719574-b82d08e5-0e46-4fe6-a098-d46c20067491.png)

I install the New Version and also create a New Project...
but stil the same Problem. )=

**Comment by Agilitytime** [comment] 2021-08-17 13:49
it must be a problem with Ubuntu... 
i did it now with CentOS and there it runs without problems! 
all ruby versions are the same

**Comment by vitobotta** [comment] 2021-08-17 13:51
I did my tests with Ubuntu, so it's unlikely. I did the tests with a VPS. I will try again, maybe I missed something else that I did during my tests.

**Comment by vitobotta** [comment] 2021-08-17 15:12
I tried again with a fresh Ubuntu VPS and all works just fine.  Can you try again following these instructions?

```bash
apt update
apt install -y git-core build-essential openssl libssl-dev zlib1g-dev
git clone https://github.com/rbenv/rbenv.git ~/.rbenv
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
source ~/.bash_profile
rbenv init
source ~/.bash_profile
git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build
rbenv install 2.7.4
rbenv global 2.7.4
ruby -v (check that it says 2.7.4)
ssh-keygen (unless you have a key already)
```

Thanks

**Comment by Agilitytime** [comment] 2021-08-17 16:31
On this way it Works without Problems!!! =) 
i hgave use GCC insteate of build-essential this was the problem i think ?

**Comment by vitobotta** [comment] 2021-08-17 16:40
@Agilitytime Even easier, I have created a Docker image so you don't have to deal with Ruby at all. It's in the README but the short version is that you can run the create/delete/upgrade commands as follows:

```bash
docker run --rm -it -v ${PWD}:/cluster -v ${HOME}/.ssh:/tmp/.ssh vitobotta/hetzner-k3s create-cluster --config-file /cluster/test.yaml
```

You run this from the directory where you have the config file for the cluster, and you need to set the kubeconfig path to /cluster/kubeconfig.

This should make things much easier for who doesn't have Ruby etc :) Please try it and let me know. Thanks!

**Comment by Agilitytime** [comment] 2021-08-17 17:30
docker run --rm -it -v ${PWD}:/cluster -v ${HOME}/.skm/ApiRancher:/tmp/.ssh vitobotta/hetzner-k3s create-cluster --config-file /cluster/cluster_config.yaml
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Traceback (most recent call last):
	9: from /usr/local/bundle/bin/hetzner-k3s:23:in `<main>'
	8: from /usr/local/bundle/bin/hetzner-k3s:23:in `load'
	7: from /usr/local/bundle/gems/hetzner-k3s-0.3.3/exe/hetzner-k3s:4:in `<top (required)>'
	6: from /usr/local/bundle/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	5: from /usr/local/bundle/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	4: from /usr/local/bundle/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	3: from /usr/local/bundle/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	2: from /usr/local/bundle/gems/hetzner-k3s-0.3.3/lib/hetzner/k3s/cli.rb:18:in `create_cluster'
	1: from /usr/local/bundle/gems/hetzner-k3s-0.3.3/lib/hetzner/k3s/cli.rb:79:in `validate_config_file'
/usr/local/bundle/gems/hetzner-k3s-0.3.3/lib/hetzner/k3s/cli.rb:159:in `validate_location': undefined method `include?' for false:FalseClass (NoMethodError)


unfortunately brings an error ...

**Comment by Agilitytime** [comment] 2021-08-17 17:35
docker run --rm -it -v ${PWD}:/cluster -v ${HOME}/.skm/ApiRancher:/tmp/.ssh vitobotta/hetzner-k3s create-cluster --config-file /cluster/cluster_config.yaml
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Traceback (most recent call last):
	9: from /usr/local/bundle/bin/hetzner-k3s:23:in `<main>'
	8: from /usr/local/bundle/bin/hetzner-k3s:23:in `load'
	7: from /usr/local/bundle/gems/hetzner-k3s-0.3.3/exe/hetzner-k3s:4:in `<top (required)>'
	6: from /usr/local/bundle/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	5: from /usr/local/bundle/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	4: from /usr/local/bundle/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	3: from /usr/local/bundle/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	2: from /usr/local/bundle/gems/hetzner-k3s-0.3.3/lib/hetzner/k3s/cli.rb:18:in `create_cluster'
	1: from /usr/local/bundle/gems/hetzner-k3s-0.3.3/lib/hetzner/k3s/cli.rb:79:in `validate_config_file'
/usr/local/bundle/gems/hetzner-k3s-0.3.3/lib/hetzner/k3s/cli.rb:159:in `validate_location': undefined method `include?' for false:FalseClass (NoMethodError)


unfortunately brings an error.
/cluster/kubeconfig and SSH Key location are correct

**Comment by vitobotta** [comment] 2021-08-17 17:42
Just to be sure, you are running the command from inside the directory with the config file, and the file is named cluster_config.yaml? Just to be sure :D

**Comment by Agilitytime** [comment] 2021-08-17 17:48
![grafik](https://user-images.githubusercontent.com/62443876/129775687-a08d9b68-4837-4d09-9d67-b4b563e04bcd.png)

**Comment by vitobotta** [comment] 2021-08-17 17:51
That error indicates that you have specified a wrong location for the servers. It should either nbg1 (Nuremberg), or fsn1 (Falkenstein) or hel1 (Helsinki). It's also possible that the location is correct but the tool couldn't temporarily fetch the available locations from the Hetzner API. I'd try again.

**Comment by vitobotta** [comment] 2021-08-17 17:51
BTW I tried with the Docker image again now and it seems to work fine.

**Comment by Agilitytime** [comment] 2021-08-18 16:49
With The docker Image i Have Problems with SSL...
But it is Possible that the Timeout is to Shurt, i test the Docker image now with a VPS

`<Thread:0x000000400cbd33e0 /usr/local/bundle/gems/hetzner-k3s-0.3.3/lib/hetzner/k3s/cluster.rb:146 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	28: from /usr/local/bundle/gems/hetzner-k3s-0.3.3/lib/hetzner/k3s/cluster.rb:146:in `block (2 levels) in create_resources'
	27: from /usr/local/bundle/gems/hetzner-k3s-0.3.3/lib/hetzner/k3s/cluster.rb:448:in `wait_for_ssh'
	26: from /usr/local/lib/ruby/2.7.0/timeout.rb:110:in `timeout'
	25: from /usr/local/lib/ruby/2.7.0/timeout.rb:33:in `catch'
	24: from /usr/local/lib/ruby/2.7.0/timeout.rb:33:in `catch'
	23: from /usr/local/lib/ruby/2.7.0/timeout.rb:33:in `block in catch'
	22: from /usr/local/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
	21: from /usr/local/bundle/gems/hetzner-k3s-0.3.3/lib/hetzner/k3s/cluster.rb:453:in `block in wait_for_ssh'
	20: from /usr/local/bundle/gems/hetzner-k3s-0.3.3/lib/hetzner/k3s/cluster.rb:453:in `loop'
	19: from /usr/local/bundle/gems/hetzner-k3s-0.3.3/lib/hetzner/k3s/cluster.rb:454:in `block (2 levels) in wait_for_ssh'
	18: from /usr/local/bundle/gems/hetzner-k3s-0.3.3/lib/hetzner/k3s/cluster.rb:468:in `ssh'
	17: from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh.rb:261:in `start'
	16: from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh.rb:261:in `ensure in start'
	15: from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:126:in `close'
	14: from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:180:in `loop'
	13: from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:180:in `loop'
	12: from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:180:in `block in loop'
	11: from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:227:in `process'
	10: from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/connection/event_loop.rb:28:in `process'
	 9: from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/connection/event_loop.rb:100:in `ev_preprocess'
	 8: from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/connection/event_loop.rb:100:in `each'
	 7: from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:248:in `ev_preprocess'
	 6: from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:545:in `dispatch_incoming_packets'
	 5: from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:190:in `poll_message'
	 4: from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:190:in `loop'
	 3: from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:193:in `block in poll_message'
	 2: from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/transport/packet_stream.rb:90:in `next_packet'
	 1: from /usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/transport/packet_stream.rb:75:in `available_for_read?'
/usr/local/bundle/gems/net-ssh-6.1.0/lib/net/ssh/transport/packet_stream.rb:75:in `select': closed stream (IOError)`


![grafik](https://user-images.githubusercontent.com/62443876/129859639-0c13f2aa-1438-4a8f-990a-8ff9fefc5f52.png)

**Comment by vitobotta** [comment] 2021-08-18 17:04
When a timeout occurs the SSH command is retried automatically. What you got is an IOError, which usually happens when there is an interruption of the connection or other network related thing (I think).

v0.3.6 now retries SSH commands when IOError occurs, so please try again but specify the `v0.3.6` tag for the Docker image.

So this time you tried with Docker from an Hetzner VPS?

**Comment by vitobotta** [comment] 2021-08-18 17:04
Can you also share the config you're using (remember to remove the token)?

**Comment by Agilitytime** [comment] 2021-08-19 12:53
With version v0.3.7 it works without problems. =)

**Comment by vitobotta** [comment] 2021-08-19 14:47
Glad to hear! I'm closing this but feel free to open another one if you still run into issues.

**Closed by vitobotta** 2021-08-19 14:47 UTC
