### ISSUE TITLE
upgrade-cluster with docker-image has unknown error

### ISSUE THREAD

**Issue by deutii** [vitobotta/hetzner-k3s#56] opened 2022-01-17 07:25 UTC
i called

```
docker run --rm -it -v ${PWD}/cluster:/cluster -v ${PWD}/.ssh:/tmp/.ssh vitobotta/hetzner-k3s:v0.5.0 upgrade-cluster --config-file /cluster/cluster_config.yaml --new-k3s-version=v1.21.8+k3s1
```
```
/usr/local/bundle/gems/subprocess-1.5.5/lib/subprocess.rb:334:in `exec': No such file or directory - bash (Errno::ENOENT)
        from /usr/local/bundle/gems/subprocess-1.5.5/lib/subprocess.rb:334:in `block in initialize'
        from /usr/local/bundle/gems/subprocess-1.5.5/lib/subprocess.rb:287:in `fork'
        from /usr/local/bundle/gems/subprocess-1.5.5/lib/subprocess.rb:287:in `initialize'
        from /usr/local/bundle/gems/subprocess-1.5.5/lib/subprocess.rb:83:in `new'
        from /usr/local/bundle/gems/subprocess-1.5.5/lib/subprocess.rb:83:in `check_call'
        from /usr/local/bundle/gems/hetzner-k3s-0.4.9/lib/hetzner/utils.rb:37:in `run'
        from /usr/local/bundle/gems/hetzner-k3s-0.4.9/lib/hetzner/k3s/cluster.rb:242:in `upgrade_cluster'
        from /usr/local/bundle/gems/hetzner-k3s-0.4.9/lib/hetzner/k3s/cluster.rb:68:in `upgrade'
        from /usr/local/bundle/gems/hetzner-k3s-0.4.9/lib/hetzner/k3s/cli.rb:47:in `upgrade_cluster'
        from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /usr/local/bundle/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
        from /usr/local/bundle/gems/hetzner-k3s-0.4.9/exe/hetzner-k3s:4:in `<top (required)>'
        from /usr/local/bundle/bin/hetzner-k3s:25:in `load'
        from /usr/local/bundle/bin/hetzner-k3s:25:in `<main>'
```
Docker run under macOS 11.6.2

I tried to build dpcker local and run again ... error same.

**Comment by deutii** [comment] 2022-01-17 07:40
this version worked 
```
docker run --rm -it -v ${PWD}/cluster:/cluster -v ${PWD}/.ssh:/tmp/.ssh vitobotta/hetzner-k3s:v0.4.8 upgrade-cluster --config-file /cluster/cluster_config.yaml --new-k3s-version=v1.21.8+k3s1
```

**Comment by Privatecoder** [comment] 2022-01-27 08:17
@vitobotta can you check this? I can confirm upgrading does not work since v0.4.9 / docker due to the error above

**Comment by vitobotta** [comment] 2022-01-27 09:20
I will try to look into it tonight. Thanks for reminding me about it

**Comment by vitobotta** [comment] 2022-01-29 10:37
I have updated the image 0.5.0 and was able to create a cluster successfully. Can you try again with this version?

**Comment by Privatecoder** [comment] 2022-01-29 11:07
hi @vitobotta! I cannot see any updates – the problem persists on 0.5.0 (which is why I wrote _since_ v0.4.9). I haven't tried creating a cluster but _upgrading_ does throw the error mentioned above.

**Comment by vitobotta** [comment] 2022-01-29 11:21
Awesome, thanks for confirming. Closing this then. Thanks again

**Closed by vitobotta** 2022-01-29 11:21 UTC
