### ISSUE TITLE
pkeys are immutable on OpenSSL 3.0

### ISSUE THREAD

**Issue by FinnRG** [vitobotta/hetzner-k3s#77] opened 2022-05-18 19:15 UTC
When trying to use the cli tool with create-cluster, I get the following error:
```
Waiting for server msostream-cpx11-master1 to be up...
#<Thread:0x00007f00a1bf54c0 /home/fgaertn/.local/share/gem/ruby/gems/hetzner-k3s-0.5.6/lib/hetzner/k3s/cluster.rb:577 run> terminated with exception (report_on_exception is true):
/usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh/transport/kex/ecdh_sha2_nistp256.rb:21:in `generate_key!': pkeys are immutable on OpenSSL 3.0 (OpenSSL::PKey::PKeyError)
	from /usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh/transport/kex/ecdh_sha2_nistp256.rb:21:in `generate_key'
	from /usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh/transport/kex/abstract.rb:32:in `initialize'
	from /usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh/transport/algorithms.rb:437:in `new'
	from /usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh/transport/algorithms.rb:437:in `exchange_keys'
	from /usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh/transport/algorithms.rb:245:in `proceed!'
	from /usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh/transport/algorithms.rb:184:in `accept_kexinit'
	from /usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:210:in `block in poll_message'
	from /usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:190:in `loop'
	from /usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:190:in `poll_message'
	from /usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:225:in `block in wait'
	from /usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:223:in `loop'
	from /usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:223:in `wait'
	from /usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:90:in `initialize'
	from /usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh.rb:251:in `new'
	from /usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh.rb:251:in `start'
	from /home/fgaertn/.local/share/gem/ruby/gems/hetzner-k3s-0.5.6/lib/hetzner/utils.rb:79:in `ssh'
	from /home/fgaertn/.local/share/gem/ruby/gems/hetzner-k3s-0.5.6/lib/hetzner/utils.rb:58:in `block (2 levels) in wait_for_ssh'
	from /home/fgaertn/.local/share/gem/ruby/gems/hetzner-k3s-0.5.6/lib/hetzner/utils.rb:57:in `loop'
	from /home/fgaertn/.local/share/gem/ruby/gems/hetzner-k3s-0.5.6/lib/hetzner/utils.rb:57:in `block in wait_for_ssh'
	from /usr/share/ruby/timeout.rb:107:in `block in timeout'
	from /usr/share/ruby/timeout.rb:36:in `block in catch'
	from /usr/share/ruby/timeout.rb:36:in `catch'
	from /usr/share/ruby/timeout.rb:36:in `catch'
	from /usr/share/ruby/timeout.rb:123:in `timeout'
	from /home/fgaertn/.local/share/gem/ruby/gems/hetzner-k3s-0.5.6/lib/hetzner/utils.rb:52:in `wait_for_ssh'
	from /home/fgaertn/.local/share/gem/ruby/gems/hetzner-k3s-0.5.6/lib/hetzner/k3s/cluster.rb:577:in `block (2 levels) in wait_for_servers'
/usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh/transport/kex/ecdh_sha2_nistp256.rb:21:in `generate_key!': pkeys are immutable on OpenSSL 3.0 (OpenSSL::PKey::PKeyError)
	from /usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh/transport/kex/ecdh_sha2_nistp256.rb:21:in `generate_key'
	from /usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh/transport/kex/abstract.rb:32:in `initialize'
	from /usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh/transport/algorithms.rb:437:in `new'
	from /usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh/transport/algorithms.rb:437:in `exchange_keys'
	from /usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh/transport/algorithms.rb:245:in `proceed!'
	from /usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh/transport/algorithms.rb:184:in `accept_kexinit'
	from /usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:210:in `block in poll_message'
	from /usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:190:in `loop'
	from /usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:190:in `poll_message'
	from /usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:225:in `block in wait'
	from /usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:223:in `loop'
	from /usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:223:in `wait'
	from /usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:90:in `initialize'
	from /usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh.rb:251:in `new'
	from /usr/share/gems/gems/net-ssh-6.1.0/lib/net/ssh.rb:251:in `start'
	from /home/fgaertn/.local/share/gem/ruby/gems/hetzner-k3s-0.5.6/lib/hetzner/utils.rb:79:in `ssh'
	from /home/fgaertn/.local/share/gem/ruby/gems/hetzner-k3s-0.5.6/lib/hetzner/utils.rb:58:in `block (2 levels) in wait_for_ssh'
	from /home/fgaertn/.local/share/gem/ruby/gems/hetzner-k3s-0.5.6/lib/hetzner/utils.rb:57:in `loop'
	from /home/fgaertn/.local/share/gem/ruby/gems/hetzner-k3s-0.5.6/lib/hetzner/utils.rb:57:in `block in wait_for_ssh'
	from /usr/share/ruby/timeout.rb:107:in `block in timeout'
	from /usr/share/ruby/timeout.rb:36:in `block in catch'
	from /usr/share/ruby/timeout.rb:36:in `catch'
	from /usr/share/ruby/timeout.rb:36:in `catch'
	from /usr/share/ruby/timeout.rb:123:in `timeout'
	from /home/fgaertn/.local/share/gem/ruby/gems/hetzner-k3s-0.5.6/lib/hetzner/utils.rb:52:in `wait_for_ssh'
	from /home/fgaertn/.local/share/gem/ruby/gems/hetzner-k3s-0.5.6/lib/hetzner/k3s/cluster.rb:577:in `block (2 levels) in wait_for_servers'
```

I use version 0.5.6.

**Comment by vitobotta** [comment] 2022-05-18 19:41
Hi, I am not sure about this with OpenSSL 3.0. I haven't come across it. I'll take a look when I have time. In the meantime you can use the Docker image so you don't need to worry about the Ruby setup.

**Comment by vitobotta** [comment] 2022-05-29 14:35
Hi, can you please add more details on how you set up Ruby?

**Comment by FinnRG** [comment] 2022-06-04 13:57
I installed CRuby with the official Fedora instructions https://developer.fedoraproject.org/tech/languages/ruby/ruby-installation.html

**Comment by krauthosting** [comment] 2022-07-09 07:48
@vitobotta BTW while using you image in podman as workaround we often face it hangs while servers all up:
![image](https://user-images.githubusercontent.com/69597449/178096855-bcbb6974-b53d-4ced-8596-d50eae245404.png)
Interrupting and restarting it helps as all server are up and can continue with deploying k3s to first master.

**Comment by vitobotta** [comment] 2022-08-12 15:05
Are you consistently able to reproduce this issue? Sorry for the long delay, I have been busy with work.

**Comment by krauthosting** [comment] 2022-08-15 12:12
@vitobotta Yes we did. As a workaround using currently podman with your image.
But love to return to Gem installation on Ubuntu 22.04 LTS with OpenSSL 3.0.
We saw other projects shifting to GnuTLS. But it's a refactoring either way.
Let us know via PM if we can assist you on your awesome work :smile:

**Comment by vitobotta** [comment] 2022-08-28 10:00
Hi @krauthosting, yesterday I released a new version (v0.6.1) with new standalone binaries that can be used directly on macOS and Linux without having to set up a Ruby environment or use the Docker image, so I suggest using those binaries moving forward as it's easier to use the tool this way. I am closing this one for that reason but feel free to reopen if you have comments about it.

**Closed by vitobotta** 2022-08-28 10:00 UTC

**Comment by krauthosting** [comment] 2022-09-02 08:20
@vitobotta Couldn't fully test it yet due to #103 but simplifies dealing with dependencies a lot :+1:

**Comment by vitobotta** [comment] 2022-09-02 12:51
Yeah I will be looking into that issue as soon as I can.
