### ISSUE TITLE
cannot connect to server

### ISSUE THREAD

**Issue by subpathdev** [vitobotta/hetzner-k3s#8] opened 2021-08-17 05:48 UTC
When I run `hetzner-k3s create-cluster --config-file hetzner-cluster.yaml` the programm finished in an error state. The connection to the server cannot be established. I'm using ssh-key to authenticate and the the key is already loaded to my keyring. After the creation of the servers, I can connect to them with `ssh root@x.x.x.x`.

```
hetzner-k3s create-cluster --config-file hetzner-cluster.yaml

Firewall already exists, skipping.


Private network already exists, skipping.


SSH key already exists, skipping.


API load balancer already exists, skipping.





Server kubeedge-cpx21-master2 already exists, skipping.

Server kubeedge-cpx21-master1 already exists, skipping.

Server kubeedge-cpx21-master3 already exists, skipping.

Server kubeedge-cpx21-pool-small-worker1 already exists, skipping.


Waiting for server kubeedge-cpx21-pool-small-worker1 to be up...
Waiting for server kubeedge-cpx21-master3 to be up...
Waiting for server kubeedge-cpx21-master1 to be up...
Waiting for server kubeedge-cpx21-master2 to be up...
#<Thread:0x00007f16c80435e0 /var/lib/gems/2.7.0/gems/hetzner-k3s-0.3.2/lib/hetzner/k3s/cluster.rb:146 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	11: from /var/lib/gems/2.7.0/gems/hetzner-k3s-0.3.2/lib/hetzner/k3s/cluster.rb:146:in `block (2 levels) in create_resources'
	10: from /var/lib/gems/2.7.0/gems/hetzner-k3s-0.3.2/lib/hetzner/k3s/cluster.rb:448:in `wait_for_ssh'
	 9: from /usr/lib/ruby/2.7.0/timeout.rb:110:in `timeout'
	 8: from /usr/lib/ruby/2.7.0/timeout.rb:33:in `catch'
	 7: from /usr/lib/ruby/2.7.0/timeout.rb:33:in `catch'
	 6: from /usr/lib/ruby/2.7.0/timeout.rb:33:in `block in catch'
	 5: from /usr/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
	 4: from /var/lib/gems/2.7.0/gems/hetzner-k3s-0.3.2/lib/hetzner/k3s/cluster.rb:453:in `block in wait_for_ssh'
	 3: from /var/lib/gems/2.7.0/gems/hetzner-k3s-0.3.2/lib/hetzner/k3s/cluster.rb:453:in `loop'
	 2: from /var/lib/gems/2.7.0/gems/hetzner-k3s-0.3.2/lib/hetzner/k3s/cluster.rb:454:in `block (2 levels) in wait_for_ssh'
	 1: from /var/lib/gems/2.7.0/gems/hetzner-k3s-0.3.2/lib/hetzner/k3s/cluster.rb:468:in `ssh'
/var/lib/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh.rb:268:in `start': Authentication failed for user root@x.x.x.x (Net::SSH::AuthenticationFailed)
```

**Comment by vitobotta** [comment] 2021-08-17 08:03
Hi, was the key already present in the project or did you let the tool create it for you?

**Comment by subpathdev** [comment] 2021-08-17 08:06
The key was already present.

**Comment by vitobotta** [comment] 2021-08-17 08:11
And you can ssh into the servers directly without problems? Do you have multiple keys in your ssh directory?

**Comment by subpathdev** [comment] 2021-08-17 08:41
Yes I can ssh into the servers directly without problems and I have multiple keys in my ssh directory

**Comment by vitobotta** [comment] 2021-08-17 09:52
Uhm I wonder if the problem is that you have multiple keys. Just to confirm, can you temporarily move the other keys to another directory and leave the relevant one, and try again? If it works, I will make a small change to the code so that it ensures that it uses the correct key when connecting to the servers, not just when creating them. Let me know.

**Comment by subpathdev** [comment] 2021-08-17 14:41
the problem still exists. I'm using ed25519 keys is that a problem?

**Comment by vitobotta** [comment] 2021-08-17 14:42
> the problem still exists. I'm using ed25519 keys is that a problem?

Not sure, I need to try since I use a simple RSA key still. So it happens also if that's the only key in ~/.ssh?

**Comment by vitobotta** [comment] 2021-08-17 14:43
BTW have you tried the latest version I released today?

**Comment by vitobotta** [comment] 2021-08-17 15:22
I was able to reproduce the issue, and it disappeared after running `ssh-add ~/.ssh/id_ed25519`. Can you try?

**Comment by subpathdev** [comment] 2021-08-18 07:22
> BTW have you tried the latest version I released today?

no I didn't use that release

I will try, when I have free time

**Comment by vitobotta** [comment] 2021-08-24 15:36
Closing for now, feel free to reopen if you have this problem again. Thanks

**Closed by vitobotta** 2021-08-24 15:36 UTC
