### ISSUE TITLE
Can't execute "hetzner-k3s create --config cluster_config.yaml" - error Unhandled exception: SSL_CTX_new: error: [...] (OpenSSL::Error)

### ISSUE THREAD

**Issue by Linutux** [vitobotta/hetzner-k3s#309] opened 2024-01-26 00:24 UTC
I Installed all required packages ("sudo dnf install libssh2 libevent libyaml pcre gmp gc-devel"), created a cluster_config.yaml and executed "hetzner-k3s create --config cluster_config.yaml".

I got the following error:

> Validating configuration...Unhandled exception: SSL_CTX_new: error:030000A9:digital envelope routines::unknown option (OpenSSL::Error)
>   from /usr/lib/crystal/core/openssl/ssl/context.cr:304:11 in 'new'
>   from /usr/lib/crystal/core/http/client.cr:136:5 in 'new_http_client'
>   from /home/runner/work/hetzner-k3s/hetzner-k3s/lib/crest/src/crest/request.cr:135:7 in 'available_releases'
>   from /home/runner/work/hetzner-k3s/hetzner-k3s/src/configuration/settings/k3s_version.cr:9:15 in 'validate'
>   from /usr/lib/crystal/core/gc/boehm.cr:132:5 in 'run:parent:program_name'
>   from /home/runner/work/hetzner-k3s/hetzner-k3s/src/hetzner-k3s.cr:10:3 in 'parse_and_run'
>   from /home/runner/work/hetzner-k3s/hetzner-k3s/src/hetzner-k3s.cr:96:1 in '__crystal_main'
>   from /usr/lib/crystal/core/crystal/main.cr:115:5 in 'main'
>   from src/env/__libc_start_main.c:95:2 in 'libc_start_main_stage2'

Can you please help me?

**Comment by vitobotta** [comment] 2024-03-06 15:37
I'm sorry for the lack of replies. I was sick and then very busy with the day job. Did you figure out what was the problem in the end?

**Comment by Linutux** [comment] 2024-03-07 13:44
Nö, I have not tried again.

I switched from Fedora to Ubuntu lately and will try again...

**Comment by vitobotta** [comment] 2024-04-16 12:24
@Linutux @rsidhaarth I have upgraded the SSH2 shard in main, can you try again? I haven't released this change yet as I want to merge other changes first.

**Comment by konczdam** [comment] 2024-04-27 15:02
I had the same error on Fedora 40.
When I built the app from the source code from the `main` branch, the error is no longer there.

I haven't found a description about the steps required to build the app locally, so I'll paste it here, hope you don't mind. 
```bash
# from the crystal documentation: https://github.com/crystal-lang/crystal/wiki/All-required-libraries#fedora
sudo dnf -y install \                                                                                                                                          
  gcc \
  gcc-c++ \
  gmp-devel \
  libbsd-devel \
  libevent-devel \
  libxml2-devel \
  libyaml-devel \
  llvm-devel \
  llvm-static \
  libstdc++-static \
  make \
  openssl-devel \
  pcre2-devel \
  redhat-rpm-config

# Needed this to overcome an error message
sudo dnf install libssh2-devel 

# install crystal
sudo snap install crystal --classic

# install dependencies
shards install --without-development

# build the app
crystal build src/hetzner-k3s.cr  
```

**Comment by vitobotta** [comment] 2024-04-27 16:22
Hi @konczdam , thanks for confirming that the problem is fixed in main! I am still working on finalising v2.0.0, which will include this together with a lot of other stuff.

**Comment by axgkl** [comment] 2024-07-15 22:56
Had the same error on my fedora.

@vitobotta supplied a Dockerfile.dev in the repo, which allows to build w/o spamming the laptop. See repo README for vscode hipsters.

Here the old fart way:

1. `podman/docker build Dockerfile.dev -t hk3`  (I had to comment out the line with the stern lib, for go incompat)
2. copy the image id from the output, docker run it and get the container id from `docker ps -a`
3. `mkdir ../fs && cd $_ && docker/podman export <that container id> | tar xfv -`
4.  `rmdir home/app/hetzner-k3s && mv ../hetzner-k3s home/app/`
5. `sudo systemd-nspawn -D .`
6. Inside: `cd /home/app/hetzner-k3s/ && crystal build ./src/hetzner-k3s.cr --verbose --static`

the first time before build you have to do a `shards init` or so, `crystal build` will tell you. 

You can do the build clearly also within the container, with the volume mounted repo but that's the way if you like to have things persistent and tend to clear your docker spam from time to time from the laptop ;-)

**Comment by vitobotta** [comment] 2024-08-12 17:58
Closing this since the problem should now be solved in v2, which I will release probably next weekend.

**Closed by vitobotta** 2024-08-12 17:58 UTC

**Comment by n7st** [comment] 2024-08-25 23:32
Running 2.0.4 on Fedora 40 is still producing the same error.

* Fedora 40
* OpenSSL 3.2.2
* Linux 6.10.6-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Aug 19 14:09:30 UTC 2024 x86_64 GNU/Linux

I checked out master, ran `crystal shards update crest` and then ran `crystal src/hetzner-k3s.cr --config /path/to/config.yml` and it completed successfully.

```diff
diff --git a/shard.lock b/shard.lock
index 87cf9f1..0f02d3e 100644
--- a/shard.lock
+++ b/shard.lock
@@ -6,7 +6,7 @@ shards:
 
   crest:
     git: https://github.com/mamantoha/crest.git
-    version: 1.3.13
+    version: 1.4.1
 
   crinja:
     git: https://github.com/straight-shoota/crinja.git
@@ -26,7 +26,7 @@ shards:
 
   http_proxy:
     git: https://github.com/mamantoha/http_proxy.git
-    version: 0.10.3
+    version: 0.12.0
 
   ipaddress:
     git: https://github.com/sija/ipaddress.cr.git
```

I'll raise a pull request with the fixed version.
