### ISSUE TITLE
Implementation of HorizontalPodAutoscaler

### ISSUE THREAD

**Issue by Freyrecorp1** [vitobotta/hetzner-k3s#140] opened 2023-01-10 16:32 UTC
One question, has anyone had problems implementing the HPA in their cluster? I have implemented it in another cluster and it works fine, but in this one it does not give me real-time cpu usage, it stays at 0.

**Comment by vitobotta** [comment] 2023-01-10 16:54
Hi, did you install metrics server in the cluster? Where/how do you see that CPU usage is zero?

**Comment by Freyrecorp1** [comment] 2023-01-10 17:40
I managed to solve it, it was a problem with my metrics file, but a new query came up, when new nodes are added to hetzner, it does not join the cluster, therefore the pods that are in the pending state cannot run yet!

**Comment by vitobotta** [comment] 2023-01-10 19:05
> I managed to solve it, it was a problem with my metrics file, but a new query came up, when new nodes are added to hetzner, it does not join the cluster, therefore the pods that are in the pending state cannot run yet!

Are these nodes created with a standard node pool or autoscaled? Which version of the tool did you use to create the cluster? Can you share your config (remove the token!)?

**Comment by Freyrecorp1** [comment] 2023-01-10 20:08
> > Logré solucionarlo, era un problema con mi archivo de métricas, pero surgió una nueva consulta, cuando se agregan nuevos nodos a hetzner, no se une al clúster, por lo tanto, ¡los pods que están en estado pendiente todavía no pueden ejecutarse!
> 
> ¿Estos nodos se crean con un grupo de nodos estándar o se escalan automáticamente? ¿Qué versión de la herramienta utilizó para crear el clúster? ¿Puede compartir su configuración (¡elimine el token!)?

I use the standard configuration, there I share my file!

hetzner_token: 
cluster_name: test-1
kubeconfig_path: "./kubeconfig"
k3s_version: v1.25.5+k3s1
public_ssh_key_path: "~/.ssh/id_rsa.pub"
private_ssh_key_path: "~/.ssh/id_rsa"
use_ssh_agent: false
ssh_allowed_networks:
  - 0.0.0.0/0
api_allowed_networks:
  - 0.0.0.0/0
schedule_workloads_on_masters: false
# image: rocky-9 # optional: default is ubuntu-22.04
# snapshot_os: microos # otional: specified the os type when using a custom snapshot
masters_pool:
  instance_type: cpx21
  instance_count: 3
  location: nbg1
  # labels:
  #   - key: purpose
  #     value: blah
  # taints:
  #   - key: something
  #     value: value1:NoSchedule
worker_node_pools:
- name: small
  instance_type: cpx21
  instance_count: 2
  location: hel1
  # labels:
  #   - key: purpose
  #     value: blah
  # taints:
  #   - key: something
  #     value: value1:NoSchedule
- name: big
  instance_type: cpx31
  instance_count: 2
  location: fsn1
  autoscaling:
    enabled: true
    min_instances: 0
    max_instances: 3
additional_packages:
- somepackage
post_create_commands:
- apt update
- apt upgrade -y
- apt autoremove -y
- shutdown -r now
# enable_encryption: true
# existing_network: <specify if you want to use an existing network, otherwise one will be created for this cluster>
# kube_api_server_args:
# - arg1
# - ...
# kube_scheduler_args:
# - arg1
# - ...
# kube_controller_manager_args:
# - arg1
# - ...
# kube_cloud_controller_manager_args:
# - arg1
# - ...
# kubelet_args:
# - arg1
# - ...
# kube_proxy_args:
# - arg1
# - ...

**Comment by Freyrecorp1** [comment] 2023-01-10 20:11
> > Logré solucionarlo, era un problema con mi archivo de métricas, pero surgió una nueva consulta, cuando se agregaron nuevos nodos a hetzner, no se une al clúster, por lo tanto, ¡los pods que están en estado pendiente todavía no pueden ejecutarse!
> 
> ¿Estos nodos se crean con un grupo de nodos estándar o se escalan automáticamente? ¿Qué versión de la herramienta mejorada para crear el clúster? ¿Puede compartir su configuración (¡eliminar el token!)?

I use the standard configuration, there I share my file!

[config_test.txt](https://github.com/vitobotta/hetzner-k3s/files/10386446/config_test.txt)

**Comment by vitobotta** [comment] 2023-01-10 20:46
How many nodes do you have now according to kubectl and how many servers do you see in the Hetzner console?

**Comment by Freyrecorp1** [comment] 2023-01-10 21:05
5 nodes and in the hetzner 6 console, the one I create when I scale the nodes is not added to the worker nodes pool

**Comment by Freyrecorp1** [comment] 2023-01-10 21:38
![Captura desde 2023-01-10 16-37-14](https://user-images.githubusercontent.com/91983888/211667721-192a021a-6413-4f6d-a814-ae4a55da71cf.png)
![Captura desde 2023-01-10 16-37-48](https://user-images.githubusercontent.com/91983888/211667723-02468b20-551f-443f-9409-5f9d6e97c725.png)

**Comment by vitobotta** [comment] 2023-01-11 17:13
Something doesn't look right: the nodes created automatically by the autoscaler have names starting with the word "autoscaled-". while your CPX31 node's name starts with "big".  If that node doesn't show up in Kubectl then please remove it from the Hetzner Console. Then please check the autoscaler's pod's logs (in the `kube-system` namespace). Do you see any errors?

**Comment by Freyrecorp1** [comment] 2023-01-11 18:17
Today I have been testing with version 1.0.5 because I did the tests yesterday with version 1.0.2, that must be why it gives this error when creating the new instances in hetznert, but today I got the error that is explained in this issue https://github.com/vitobotta/hetzner-k3s/issues/141, the ssh is without passwords!

**Comment by vitobotta** [comment] 2023-01-11 18:37
> Today I have been testing with version 1.0.5 because I did the tests yesterday with version 1.0.2, that must be why it gives this error when creating the new instances in hetznert, but today I got the error that is explained in this issue #141, the ssh is without passwords!

Better to continue in that thread about this since it's a separate issue.

**Comment by vitobotta** [comment] 2023-01-13 19:38
Can I close this issue since we are following up to the time out issue in another one?

**Comment by vitobotta** [comment] 2023-01-22 10:24
Closing since you confirmed in another issue that you got your cluster working. :)

**Closed by vitobotta** 2023-01-22 10:24 UTC
