### ISSUE TITLE
Endless Waiting for server to be up...

### ISSUE THREAD

**Issue by wiemann** [vitobotta/hetzner-k3s#96] opened 2022-08-28 09:25 UTC
Getting an endless "Waiting for server XY to be up" for all machines (master & workers) on 0.6.1 on Apple Silicon.

Config:
```
---
hetzner_token: XXX
cluster_name: cluster_XY
kubeconfig_path: "./kubeconfig"
k3s_version: v1.23.3+k3s1
public_ssh_key_path: "~/.ssh/id_rsa.pub"
private_ssh_key_path: "~/.ssh/id_rsa"
ssh_allowed_networks:
  - 0.0.0.0/0
api_allowed_networks:
  - 0.0.0.0/0
verify_host_key: false
location: fsn1
schedule_workloads_on_masters: false
masters:
  instance_type: cpx11
  instance_count: 1
worker_node_pools:
  - name: small
    instance_type: cx31
    instance_count: 3
enable_encryption: true
```

**Comment by Privatecoder** [comment] 2022-08-28 09:27
Is this an older Cluster? If so, check [this](https://github.com/vitobotta/hetzner-k3s/issues/80).

**Comment by vitobotta** [comment] 2022-08-28 09:29
I need to update the README with that information

**Comment by wiemann** [comment] 2022-08-28 09:37
No, I saw that issue and it didn't help me because the cluster is brand-new.

**Comment by vitobotta** [comment] 2022-08-28 09:45
How did you install the tool? With the Ruby gem, Docker or the new brew/binaries that I released yesterday?

**Comment by vitobotta** [comment] 2022-08-28 09:48
Also how long did you wait? With a recent update the all the os packages get upgraded automatically when the servers are created and then rebooted, so it may take a little while sometimes.

**Comment by vitobotta** [comment] 2022-08-28 10:02
One more thing: the tool is idempotent. If for some reason it got stuck you can interrupt and run it again and it will pick from where it left. Can you please try again and let me know if the issue still persists? I tried creating a cluster now just in case something went wrong with the last release but I didn't have any problems.

**Comment by wiemann** [comment] 2022-08-28 11:55
I used binary as recommended to use with Apple Silicon / ARM in Readme. Will try again later today as recommended

**Comment by vitobotta** [comment] 2022-08-28 11:57
Ok, let me know how it goes. Thanks

**Comment by wiemann** [comment] 2022-08-28 17:09
No, it 's still waiting for the servers to become available

**Comment by vitobotta** [comment] 2022-08-28 17:19
I'll follow up via email for now since some information might be private, then will update the issue with our findings.

**Comment by vitobotta** [comment] 2022-08-29 19:54
Closing this for now since the author of the issue has decided not to use Kubernetes. I cannot reproduce the issue myself with various SSH keys (it turned out from an investigation with @wiemann's help that the problem is in the SSH connections) and an attempt to fix with a custom prerelease didn't help. I will resume the investigation if it happens again to someone else who can help debugging / finding the solution.

**Closed by vitobotta** 2022-08-29 19:54 UTC
