### ISSUE TITLE
releases subcommand throws error on Linux

### ISSUE THREAD

**Issue by geewiz** [vitobotta/hetzner-k3s#100] opened 2022-08-30 15:03 UTC
I read your request on the GoRails Discord to test the Linux version. I'm getting this on Manjaro Linux:

```
➜ hetzner-k3s version                
0.6.1

➜ hetzner-k3s releases
Cannot fetch the releases with Github API, please try again later. This may be due to API rate limits.
Traceback (most recent call last):
	5: from /__enclose_io_memfs__/local/exe/hetzner-k3s:7:in `<main>'
	4: from /__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	3: from /__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	2: from /__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	1: from /__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
/__enclose_io_memfs__/local/lib/hetzner/k3s/cli.rb:52:in `releases': undefined method `each' for nil:NilClass (NoMethodError)
```

I didn't touch my laptop in hours before installing the application, so it can't be a rate limit issue.

**Comment by vitobotta** [comment] 2022-08-30 15:09
Hi, does it happen consistently? Have you by chance tried the command multiple times? Github API has an annoying low rate limit if you don't provide a token. I should add a token support to the config.

**Comment by vitobotta** [comment] 2022-08-30 15:11
Hi, and thanks :)

I replied in the issue. Did you try the command many times by chance?
Does it happen even with a VPN? (to change IP)

**Comment by geewiz** [comment] 2022-08-30 15:47
It did fail the first time I tried it, and the two times after that. Using a VPN connection didn't seem to help either.

**Comment by vitobotta** [comment] 2022-08-30 15:59
Super weird, I cannot reproduce on Linux. I have tried Ubuntu. I will see if I can try Manjaro.

**Comment by geewiz** [comment] 2022-08-30 17:00
I’m travelling this week and will help you investigate this in detail when I’m back home.

**Comment by vitobotta** [comment] 2022-08-30 17:22
Sure, thanks a lot!

**Comment by vitobotta** [comment] 2022-08-30 17:27
I'l close it for now since I am trying to keep open actionable issues only. We'll reopen when you can help with this :)

**Closed by vitobotta** 2022-08-30 17:27 UTC
