### ISSUE TITLE
New ARM worker node images not matching architecture (autoscaler)

### ISSUE THREAD

**Issue by carlesjavierre** [vitobotta/hetzner-k3s#207] opened 2023-04-25 18:53 UTC
Hello and thanks for actively maintaining this amazing project!

Here's a few log lines of the issue. It's on the cluster-autoscaler.

![image](https://user-images.githubusercontent.com/12613547/234369558-66e4955a-971b-489d-b3c8-c3a04e6f6a20.png)

The master node is created correctly, but no workers are created. It works ONLY when I create them from your script.

I've inspected the HCLOUD API and it seems like whenever you search for ubuntu, the ARM image is on the second page. Maybe since the one creating it is the cluster autoscaler it doesn't know the architecture it goes for the first one it finds? Maybe there's an architecture parameter that can be defined on the cluster-autoscaler?

This is the configuration I have on my cluster, if that helps you replicate the issue:

```yaml
hetzner_token: token
cluster_name: cluster
kubeconfig_path: "./kubeconfig"
k3s_version: v1.26.2+k3s1
public_ssh_key_path: "~/.ssh/id_ed25519.pub"
private_ssh_key_path: "~/.ssh/id_ed25519"
use_ssh_agent: false
ssh_allowed_networks:
  - 0.0.0.0/0
api_allowed_networks:
  - 0.0.0.0/0
private_network_subnet: 10.0.0.0/16
schedule_workloads_on_masters: false
image: ubuntu-22.04
masters_pool:
  instance_type: cax11
  instance_count: 1
  location: fsn1
worker_node_pools:
- name: small-autoscaled
  instance_type: cax21
  instance_count: 1
  location: fsn1
  autoscaling:
    enabled: true
    min_instances: 1
    max_instances: 5
```

**Comment by vitobotta** [comment] 2023-04-25 20:48
Ok I was able to reproduce the problem. The fix is to specify in the settings the image by ID instead of name, so for Ubuntu 22.04 on ARM it's `103908130`.  If you set the image to that value then the autoscaler correctly creates the nodes.

You can get the list of images with their IDs with the command:

```bash
curl \
	-H "Authorization: Bearer $API_TOKEN" \
	'https://api.hetzner.cloud/v1/images'
```

The problem is that until now we only had x86 nodes so my tool currently allows you to specify the image at root level in the configuration, and that setting applies to **all** nodes, included autoscaled ones. If you are planning to have a cluster with only ARM nodes this is fine, but right now you cannot have a mixed cluster because you can only specify one image.

I need to make a release so you can specify the image for each node pool separately, which will let you have x86 pools as well as arm pools.

The current version also doesn't allow you to use Hetzner's block storage with ARM instances. I need to update the CSI driver to 2.3.2 which supports them. 

If this is not urgent for you right now, I will make a new release likely in the weekend if I don't have time before that. If you need it urgently I can try tomorrow night but I can't promise it :)

**Comment by carlesjavierre** [comment] 2023-04-25 21:07
Hello,

Yes, I figured IDs would work. However if they get updated/deprecated it might stop working and that would not be a "permanent fix".

Yes. I have tried the hardcoded 2.3.2 CSI driver and it works flawlessly.

I have no urgency whatsoever, I only wanted to try if ARM was ready for goodness. Feel free to do it whenever you want!

**Comment by vitobotta** [comment] 2023-04-25 21:08
👍

**Comment by vitobotta** [comment] 2023-04-26 18:45
I have released v1.1.2 with support for ARM instances. It updates the CSI driver and the CCM and allows you to specify a different image for each static node pool and an `autoscaling_image` for autoscaled node pools, so you can specify the image for ARM. See README for details. Closing for now but feel free to reopen or open a new issue if needed :)

**Comment by carlesjavierre** [comment] 2023-04-26 19:13
Sounds good! Thanks for the fast update as well. 

Howevee, I wonder if the images would stop working because they're marked as deprecated. I'm guessing its a limitation from the autoscaler, which I don't know if it's aware of arm images. Maybe they need to update the plugin that helps choose the images? 

And yes, everyone could maintain a separate snapshot that would be permanently static and that would work fine and not have any depreciations. I ask for too much convenience I guess :P

One idea could be (if the other isn't possible) if it knows its an arm type, search for the name and look for the latest arm image ID of that version (because the autoscaler doesn't know). That would at least make your choice the latest one at that time and maybe last longer without issues. A simple redeploy or an automatic redeploy of the cluster would get the new ID and update it.

PS: don't call me lazy 😂 just trying to give ideas.

**Comment by vitobotta** [comment] 2023-04-26 19:36
Which images do you see as deprecated?

I checked with this command:

```bash
curl \
-H "Authorization: Bearer $API_TOKEN" \
'https://api.hetzner.cloud/v1/images?per_page=100' | jq '.images | map(select(.architecture == "arm"))'
```

And they all seem to have `deprecated: null`

**Comment by carlesjavierre** [comment] 2023-04-26 19:48
I mean in the future there might be issues if we hardcode IDs and they decide to deprecate one or disappears (if they update them regularly and gets new IDs? I don't know if they do that). In the mean it's perfectly fine. Just trying to think ahead of time.

**Comment by vitobotta** [comment] 2023-04-26 21:08
I see now what I mean. I guess it can happen, but this would only affect new servers. In that case creating servers would fail and the error message from the Hetzner, I guess, would suggest what's the issue i.e. that you need to change image.

**Comment by carlesjavierre** [comment] 2023-04-26 21:12
The "issue" would be that if I need the cluster to autoscale, it would fail and the system might collapse. Obviously if it's done manually I would notice.

Having "my own" permanent images would fix it, so it's something at least.

**Comment by vitobotta** [comment] 2023-04-26 21:22
Yeah, makes sense. I hope Hetzner changes their image support with something more permanent to avoid this scenario.

**Comment by vitobotta** [comment] 2023-04-27 16:54
That's awesome. I will update as soon as the new version is out.

**Comment by vitobotta** [comment] 2023-05-10 16:17
Hi @carlesjavierre I also got a notification from the repo about it. Will release a new version when I have time. I will probably make versions configurable.

**Comment by carlesjavierre** [comment] 2023-06-28 15:02
Hello,

Since this thread was already marked as completed, maybe it slipped under the radar. I've seen newer issues were "solved" (answered, at least) and I just wanted to make sure it wasn't the case.

Thanks for everything!

**Comment by vitobotta** [comment] 2023-06-28 17:59
@carlesjavierre I may have closed it by mistake, sorry :)

**Comment by vitobotta** [comment] 2023-06-29 09:55
I've released 1.1.3 which upgrades the cluster autoscaler to the latest version. Please check it out and let me know if you encounter any issue with this change.

**Comment by flemzord** [comment] 2023-08-01 20:46
@vitobotta I add a link with the PR fix this issue :)

**Comment by carlesjavierre** [comment] 2023-08-03 13:54
Completely forgot to check it. Yes, despites having upadted the version that specific feature is on the 1.27 branch not the 1.26 branch. The PR is correct.

**Comment by vitobotta** [comment] 2023-09-22 18:46
#259 has been merged so I am closing. Feel free to open a new one if you have problems with the new version of the autoscaler.

**Closed by vitobotta** 2023-09-22 18:46 UTC
